
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package itaf.WsServiceProviderTypeService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-18T14:35:59.084+08:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WsServiceProviderTypeService",
                      portName = "WsServiceProviderTypeServiceImplPort",
                      targetNamespace = "http://impl.merchant.server.ws.framework.itaf/",
                      wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsServiceProviderTypeService?wsdl",
                      endpointInterface = "itaf.WsServiceProviderTypeService.WsServiceProviderTypeService")
                      
public class WsServiceProviderTypeServiceImplPortImpl implements WsServiceProviderTypeService {

    private static final Logger LOG = Logger.getLogger(WsServiceProviderTypeServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see itaf.WsServiceProviderTypeService.WsServiceProviderTypeService#syncToClient(java.lang.String  updateTime )*
     */
    public itaf.WsServiceProviderTypeService.WsPageResult syncToClient(java.lang.String updateTime) { 
        LOG.info("Executing operation syncToClient");
        System.out.println(updateTime);
        try {
            itaf.WsServiceProviderTypeService.WsPageResult _return = new itaf.WsServiceProviderTypeService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(-167461159);
            _return.setCurrentPage(1113874662);
            _return.setPageSize(409275002);
            _return.setStatus("Status1934059184");
            _return.setStatusCode("StatusCode527864334");
            _return.setTotalCount(-612812309);
            _return.setTotalPage(-975460556);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
