package itaf.WsServiceProviderTypeService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import itaf.framework.ws.server.merchant.impl.WsServiceProviderTypeService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1 2014-09-18T14:35:59.037+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class WsServiceProviderTypeService_WsServiceProviderTypeServiceImplPort_Client {

	private static final QName SERVICE_NAME = new QName(
			"http://impl.merchant.server.ws.framework.itaf/",
			"WsServiceProviderTypeService");

	private WsServiceProviderTypeService_WsServiceProviderTypeServiceImplPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = WsServiceProviderTypeService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		WsServiceProviderTypeService ss = new WsServiceProviderTypeService(
				wsdlURL, SERVICE_NAME);
		itaf.WsServiceProviderTypeService.WsServiceProviderTypeService port = ss
				.getWsServiceProviderTypeServiceImplPort();

		{
			System.out.println("Invoking syncToClient...");
			java.lang.String _syncToClient_updateTime = "2011-01-01 01:02:02.001";
			itaf.WsServiceProviderTypeService.WsPageResult _syncToClient__return = port
					.syncToClient(_syncToClient_updateTime);
			System.out.println("syncToClient.result=" + _syncToClient__return);

		}

		System.exit(0);
	}

}
