package itaf.WsUserTakeDeliveryAddressService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import itaf.framework.ws.server.consumer.impl.WsUserTakeDeliveryAddressService;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.1 2014-09-25T10:48:09.834+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class WsUserTakeDeliveryAddressService_WsUserTakeDeliveryAddressServiceImplPort_Client {

	private static final QName SERVICE_NAME = new QName(
			"http://impl.consumer.server.ws.framework.itaf/",
			"WsUserTakeDeliveryAddressService");

	private WsUserTakeDeliveryAddressService_WsUserTakeDeliveryAddressServiceImplPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = WsUserTakeDeliveryAddressService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		WsUserTakeDeliveryAddressService ss = new WsUserTakeDeliveryAddressService(
				wsdlURL, SERVICE_NAME);
		itaf.WsUserTakeDeliveryAddressService.WsUserTakeDeliveryAddressService port = ss
				.getWsUserTakeDeliveryAddressServiceImplPort();

		{
			System.out.println("Invoking findListByUserId...");
			java.lang.Long _findListByUserId_userId = Long
					.valueOf(-625905507068189968l);
			itaf.WsUserTakeDeliveryAddressService.WsPageResult _findListByUserId__return = port
					.findListByUserId(_findListByUserId_userId);
			System.out.println("findListByUserId.result="
					+ _findListByUserId__return);

		}
		{
			System.out.println("Invoking getById...");
			java.lang.Long _getById_id = Long.valueOf(7432662689438886112l);
			itaf.WsUserTakeDeliveryAddressService.WsPageResult _getById__return = port
					.getById(_getById_id);
			System.out.println("getById.result=" + _getById__return);

		}
		{
			System.out.println("Invoking saveOrUpdate...");
			itaf.WsUserTakeDeliveryAddressService.BzUserTakeDeliveryAddressDto _saveOrUpdate_dto = new itaf.WsUserTakeDeliveryAddressService.BzUserTakeDeliveryAddressDto();
			_saveOrUpdate_dto.setId(Long.valueOf(7190715658597839322l));
			_saveOrUpdate_dto.setObjId(Long.valueOf(869944080701012560l));
			_saveOrUpdate_dto.setCreatedBy(Long.valueOf(-4867625969641112716l));
			_saveOrUpdate_dto.setCreatedDate(javax.xml.datatype.DatatypeFactory
					.newInstance().newXMLGregorianCalendar(
							"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dto.setUpdatedBy(Long.valueOf(-1047148707178529769l));
			_saveOrUpdate_dto.setUpdatedDate(javax.xml.datatype.DatatypeFactory
					.newInstance().newXMLGregorianCalendar(
							"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dto.setMarkForDelete(Boolean.valueOf(false));
			itaf.WsUserTakeDeliveryAddressService.SysUserDto _saveOrUpdate_dtoSysUserDto = new itaf.WsUserTakeDeliveryAddressService.SysUserDto();
			_saveOrUpdate_dtoSysUserDto.setId(Long
					.valueOf(-3532385710331563817l));
			_saveOrUpdate_dtoSysUserDto.setObjId(Long
					.valueOf(-6024858024077021838l));
			_saveOrUpdate_dtoSysUserDto.setCreatedBy(Long
					.valueOf(6414114682029249458l));
			_saveOrUpdate_dtoSysUserDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dtoSysUserDto.setUpdatedBy(Long
					.valueOf(-5284231273423821516l));
			_saveOrUpdate_dtoSysUserDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dtoSysUserDto.setMarkForDelete(Boolean.valueOf(true));
			_saveOrUpdate_dtoSysUserDto.setUsername("Username-183986319");
			_saveOrUpdate_dtoSysUserDto.setPassword("Password783414742");
			_saveOrUpdate_dtoSysUserDto.setMobile("Mobile201527503");
			_saveOrUpdate_dtoSysUserDto.setType(Long
					.valueOf(-6104048157325610742l));
			_saveOrUpdate_dtoSysUserDto.setEmail("Email-2112295919");
			_saveOrUpdate_dtoSysUserDto.setNickname("Nickname-659763602");
			java.util.List<itaf.WsUserTakeDeliveryAddressService.SysRoleDto> _saveOrUpdate_dtoSysUserDtoSysRoles = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.SysRoleDto>();
			itaf.WsUserTakeDeliveryAddressService.SysRoleDto _saveOrUpdate_dtoSysUserDtoSysRolesVal1 = new itaf.WsUserTakeDeliveryAddressService.SysRoleDto();
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1.setId(Long
					.valueOf(-6013728483522759810l));
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1.setObjId(Long
					.valueOf(-3825222759100844814l));
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1.setCreatedBy(Long
					.valueOf(-2450243434739188164l));
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1.setUpdatedBy(Long
					.valueOf(-2448528371634715918l));
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1.setMarkForDelete(Boolean
					.valueOf(false));
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1
					.setNameZh("NameZh-895521337");
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1
					.setNameEn("NameEn-1531365029");
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1
					.setDescription("Description-1852016125");
			java.util.List<itaf.WsUserTakeDeliveryAddressService.SysResourceDto> _saveOrUpdate_dtoSysUserDtoSysRolesVal1SysResourceDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.SysResourceDto>();
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1
					.getSysResourceDtos()
					.addAll(_saveOrUpdate_dtoSysUserDtoSysRolesVal1SysResourceDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.SysUserDto> _saveOrUpdate_dtoSysUserDtoSysRolesVal1SysUserDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.SysUserDto>();
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1.getSysUserDtos().addAll(
					_saveOrUpdate_dtoSysUserDtoSysRolesVal1SysUserDtos);
			_saveOrUpdate_dtoSysUserDtoSysRoles
					.add(_saveOrUpdate_dtoSysUserDtoSysRolesVal1);
			_saveOrUpdate_dtoSysUserDto.getSysRoles().addAll(
					_saveOrUpdate_dtoSysUserDtoSysRoles);
			_saveOrUpdate_dto.setSysUserDto(_saveOrUpdate_dtoSysUserDto);
			itaf.WsUserTakeDeliveryAddressService.BzPositionDto _saveOrUpdate_dtoBzPositionDto = new itaf.WsUserTakeDeliveryAddressService.BzPositionDto();
			_saveOrUpdate_dtoBzPositionDto.setId(Long
					.valueOf(-1997312535064579434l));
			_saveOrUpdate_dtoBzPositionDto.setObjId(Long
					.valueOf(6276483920438176312l));
			_saveOrUpdate_dtoBzPositionDto.setCreatedBy(Long
					.valueOf(-5696210349690277318l));
			_saveOrUpdate_dtoBzPositionDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dtoBzPositionDto.setUpdatedBy(Long
					.valueOf(3650390184666870252l));
			_saveOrUpdate_dtoBzPositionDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dtoBzPositionDto.setMarkForDelete(Boolean
					.valueOf(true));
			_saveOrUpdate_dtoBzPositionDto.setX(new java.math.BigDecimal(
					"-7455613776411179734.2463176244027677157"));
			_saveOrUpdate_dtoBzPositionDto.setY(new java.math.BigDecimal(
					"-5368448631025823317.3839763831765575783"));
			_saveOrUpdate_dtoBzPositionDto.setZ(new java.math.BigDecimal(
					"1544749384153697054.123394325123774595"));
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzUserPositionDto> _saveOrUpdate_dtoBzPositionDtoBzUserPositionDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzUserPositionDto>();
			itaf.WsUserTakeDeliveryAddressService.BzUserPositionDto _saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1 = new itaf.WsUserTakeDeliveryAddressService.BzUserPositionDto();
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1.setId(Long
					.valueOf(2801639246742586383l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1.setObjId(Long
					.valueOf(-5362373423403425075l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1
					.setCreatedBy(Long.valueOf(5457143797930244384l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1
					.setUpdatedBy(Long.valueOf(7596284564551586709l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1
					.setMarkForDelete(Boolean.valueOf(false));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1
					.setSysUserId(Long.valueOf(3109270262115460837l));
			itaf.WsUserTakeDeliveryAddressService.SysUserDto _saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto = new itaf.WsUserTakeDeliveryAddressService.SysUserDto();
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setId(Long.valueOf(-7846503558606577507l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setObjId(Long.valueOf(1409543848610487660l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setCreatedBy(Long.valueOf(-975348938953285066l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setUpdatedBy(Long.valueOf(-653180908952109520l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setMarkForDelete(Boolean.valueOf(true));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setUsername("Username-1315655590");
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setPassword("Password-721470262");
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setMobile("Mobile1631487651");
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setType(Long.valueOf(-1810788435173130915l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setEmail("Email-1992915422");
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setNickname("Nickname-494573082");
			java.util.List<itaf.WsUserTakeDeliveryAddressService.SysRoleDto> _saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDtoSysRoles = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.SysRoleDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.getSysRoles()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDtoSysRoles);
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1
					.setSysUserDto(_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto);
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1
					.setBzPositionId(Long.valueOf(6105176808048785850l));
			itaf.WsUserTakeDeliveryAddressService.BzPositionDto _saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto = new itaf.WsUserTakeDeliveryAddressService.BzPositionDto();
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.setId(Long.valueOf(2952963467029583688l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.setObjId(Long.valueOf(6771027052998518839l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.setCreatedBy(Long.valueOf(-4110448840872139508l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.setUpdatedBy(Long.valueOf(3425075766925496390l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.setMarkForDelete(Boolean.valueOf(false));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.setX(new java.math.BigDecimal(
							"-4108299437933078475.8169092864660438563"));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.setY(new java.math.BigDecimal(
							"769583267962282589.8347944821148252319"));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.setZ(new java.math.BigDecimal(
							"-1809742601523558556.8749565887481151650"));
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzUserPositionDto> _saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDtoBzUserPositionDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzUserPositionDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.getBzUserPositionDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDtoBzUserPositionDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzUserDeliveryAddressDto> _saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDtoBzUserDeliveryAddresseDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzUserDeliveryAddressDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.getBzUserDeliveryAddresseDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDtoBzUserDeliveryAddresseDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzProductDto> _saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDtoBzProductDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzProductDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.getBzProductDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDtoBzProductDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzUserTakeDeliveryAddressDto> _saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDtoBzUserTakeDeliveryAddresseDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzUserTakeDeliveryAddressDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.getBzUserTakeDeliveryAddresseDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDtoBzUserTakeDeliveryAddresseDtos);
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1
					.setBzPositionDto(_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto);
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1
					.setServiceCoverage(Long.valueOf(604978258708055490l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtos
					.add(_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1);
			_saveOrUpdate_dtoBzPositionDto.getBzUserPositionDtos().addAll(
					_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzUserDeliveryAddressDto> _saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzUserDeliveryAddressDto>();
			itaf.WsUserTakeDeliveryAddressService.BzUserDeliveryAddressDto _saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1 = new itaf.WsUserTakeDeliveryAddressService.BzUserDeliveryAddressDto();
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setId(Long.valueOf(-3544266980681944208l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setObjId(Long.valueOf(-570845910022699153l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setCreatedBy(Long.valueOf(1574652730373333668l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setUpdatedBy(Long.valueOf(8551648721803562720l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setMarkForDelete(Boolean.valueOf(false));
			itaf.WsUserTakeDeliveryAddressService.SysUserDto _saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto = new itaf.WsUserTakeDeliveryAddressService.SysUserDto();
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setId(Long.valueOf(106822522142844800l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setObjId(Long.valueOf(3797096548735675653l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setCreatedBy(Long.valueOf(-8946015746726644986l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setUpdatedBy(Long.valueOf(-7640511120816571782l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setMarkForDelete(Boolean.valueOf(false));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setUsername("Username-1956412333");
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setPassword("Password-325887433");
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setMobile("Mobile-1388262554");
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setType(Long.valueOf(6633910764149176914l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setEmail("Email-1576794668");
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setNickname("Nickname-1072778106");
			java.util.List<itaf.WsUserTakeDeliveryAddressService.SysRoleDto> _saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDtoSysRoles = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.SysRoleDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.getSysRoles()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDtoSysRoles);
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setSysUserDto(_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto);
			itaf.WsUserTakeDeliveryAddressService.BzPositionDto _saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto = new itaf.WsUserTakeDeliveryAddressService.BzPositionDto();
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.setId(Long.valueOf(3730366879016698318l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.setObjId(Long.valueOf(-4843433085687661037l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.setCreatedBy(Long.valueOf(-5507202437693166795l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.setUpdatedBy(Long.valueOf(7366408833705048355l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.setMarkForDelete(Boolean.valueOf(false));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.setX(new java.math.BigDecimal(
							"2941229472767811282.4387780711112018584"));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.setY(new java.math.BigDecimal(
							"4742932579092272333.7063747116644969135"));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.setZ(new java.math.BigDecimal(
							"-93381569938440825.3295540370884836092"));
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzUserPositionDto> _saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDtoBzUserPositionDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzUserPositionDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.getBzUserPositionDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDtoBzUserPositionDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzUserDeliveryAddressDto> _saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDtoBzUserDeliveryAddresseDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzUserDeliveryAddressDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.getBzUserDeliveryAddresseDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDtoBzUserDeliveryAddresseDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzProductDto> _saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDtoBzProductDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzProductDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.getBzProductDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDtoBzProductDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzUserTakeDeliveryAddressDto> _saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDtoBzUserTakeDeliveryAddresseDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzUserTakeDeliveryAddressDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.getBzUserTakeDeliveryAddresseDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDtoBzUserTakeDeliveryAddresseDtos);
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setBzPositionDto(_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto);
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setAddressTag("AddressTag899175422");
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setAddress("Address1971187590");
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setContactPerson("ContactPerson-1058579582");
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setContactNo("ContactNo-1705306299");
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setPostcode("Postcode-1205325817");
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtos
					.add(_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1);
			_saveOrUpdate_dtoBzPositionDto
					.getBzUserDeliveryAddresseDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzProductDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzProductDto>();
			itaf.WsUserTakeDeliveryAddressService.BzProductDto _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1 = new itaf.WsUserTakeDeliveryAddressService.BzProductDto();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1.setId(Long
					.valueOf(-6961510854192584276l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1.setObjId(Long
					.valueOf(3183363122162476909l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1.setCreatedBy(Long
					.valueOf(-9107940216668427399l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.896+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1.setUpdatedBy(Long
					.valueOf(7868036144562754189l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setMarkForDelete(Boolean.valueOf(false));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setBzMerchantId(Long.valueOf(-2807506160920087138l));
			itaf.WsUserTakeDeliveryAddressService.BzMerchantDto _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDto = new itaf.WsUserTakeDeliveryAddressService.BzMerchantDto();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDto
					.setId(Long.valueOf(-4514202738078151877l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDto
					.setObjId(Long.valueOf(-7606778329269295765l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDto
					.setCreatedBy(Long.valueOf(4627408233317289681l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDto
					.setUpdatedBy(Long.valueOf(4958613127028651366l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDto
					.setMarkForDelete(Boolean.valueOf(true));
			itaf.WsUserTakeDeliveryAddressService.BzServiceProviderTypeDto _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto = new itaf.WsUserTakeDeliveryAddressService.BzServiceProviderTypeDto();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setId(Long.valueOf(3138601451110514725l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setObjId(Long.valueOf(8345951901082439279l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setCreatedBy(Long.valueOf(7038981512148179115l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setUpdatedBy(Long.valueOf(6307768228315492412l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setMarkForDelete(Boolean.valueOf(false));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setParentId(Long.valueOf(-7900289121208361553l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setOrderNo(Long.valueOf(1097131535734841089l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setIsLeaf(Boolean.valueOf(true));
			itaf.WsUserTakeDeliveryAddressService.BzServiceProviderTypeDto _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto = new itaf.WsUserTakeDeliveryAddressService.BzServiceProviderTypeDto();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setId(Long.valueOf(3375011585202359424l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setObjId(Long.valueOf(-1809006222766159926l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setCreatedBy(Long.valueOf(-2801111320319727435l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setUpdatedBy(Long.valueOf(927210503293521071l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setMarkForDelete(Boolean.valueOf(false));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setParentId(Long.valueOf(-6952829110770205008l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setOrderNo(Long.valueOf(-7562112982100257136l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setIsLeaf(Boolean.valueOf(false));
			itaf.WsUserTakeDeliveryAddressService.BzServiceProviderTypeDto _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto = new itaf.WsUserTakeDeliveryAddressService.BzServiceProviderTypeDto();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setId(Long.valueOf(-3583868497283512953l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setObjId(Long.valueOf(-7390848480627075707l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setCreatedBy(Long.valueOf(-3819344619335220775l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setUpdatedBy(Long.valueOf(-4936453739981975369l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setMarkForDelete(Boolean.valueOf(true));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setParentId(Long.valueOf(-3450463669039516469l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setOrderNo(Long.valueOf(-2082365036070125669l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setIsLeaf(Boolean.valueOf(true));
			itaf.WsUserTakeDeliveryAddressService.BzServiceProviderTypeDto _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto = new itaf.WsUserTakeDeliveryAddressService.BzServiceProviderTypeDto();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setId(Long.valueOf(-6308769248936083717l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setObjId(Long.valueOf(4547870472435151615l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setCreatedBy(Long.valueOf(-2172083158114347309l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setUpdatedBy(Long.valueOf(-5377000127688070142l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setMarkForDelete(Boolean.valueOf(true));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setParentId(Long.valueOf(-9168838400110867649l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setOrderNo(Long.valueOf(-1567196490585551685l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setIsLeaf(Boolean.valueOf(false));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setParentDto(null);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setTypeName("TypeName-424780585");
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setTypeCode("TypeCode928395614");
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzServiceProviderTypeDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDtoChildrenDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzServiceProviderTypeDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.getChildrenDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDtoChildrenDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzDistributionCompanyDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDtoBzDistributionCompanieDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzDistributionCompanyDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.getBzDistributionCompanieDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDtoBzDistributionCompanieDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzMerchantDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDtoBzMerchantDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzMerchantDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.getBzMerchantDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDtoBzMerchantDtos);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setParentDto(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setTypeName("TypeName1411068507");
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setTypeCode("TypeCode2064373195");
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzServiceProviderTypeDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoChildrenDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzServiceProviderTypeDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.getChildrenDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoChildrenDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzDistributionCompanyDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoBzDistributionCompanieDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzDistributionCompanyDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.getBzDistributionCompanieDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoBzDistributionCompanieDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzMerchantDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoBzMerchantDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzMerchantDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.getBzMerchantDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoBzMerchantDtos);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setParentDto(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setTypeName("TypeName-1510950581");
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setTypeCode("TypeCode-1270261039");
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzServiceProviderTypeDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoChildrenDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzServiceProviderTypeDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.getChildrenDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoChildrenDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzDistributionCompanyDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoBzDistributionCompanieDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzDistributionCompanyDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.getBzDistributionCompanieDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoBzDistributionCompanieDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzMerchantDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoBzMerchantDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzMerchantDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.getBzMerchantDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoBzMerchantDtos);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setParentDto(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setTypeName("TypeName-1032645327");
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setTypeCode("TypeCode-1708948301");
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzServiceProviderTypeDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoChildrenDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzServiceProviderTypeDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.getChildrenDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoChildrenDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzDistributionCompanyDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoBzDistributionCompanieDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzDistributionCompanyDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.getBzDistributionCompanieDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoBzDistributionCompanieDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzMerchantDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoBzMerchantDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzMerchantDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.getBzMerchantDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoBzMerchantDtos);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDto
					.setBzServiceProviderTypeDto(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setBzMerchantDto(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDto);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setProductName("ProductName54952244");
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setProductPrice(new java.math.BigDecimal(
							"1888083803319588842.8172626580033368151"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setProductPurchasePrice(new java.math.BigDecimal(
							"3642329350123729520.3810731749247804135"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setProductColor("ProductColor-2057694489");
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setProductDescription("ProductDescription913817727");
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setProductOnSale(Long.valueOf(-3966132178973705422l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setIsStockLimitless(Long.valueOf(6471696980230464887l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setIsShelfLimitless(Long.valueOf(-1089739520273361503l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setIsStockSupport(Long.valueOf(4795733994874804595l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setIsShelfSupport(Long.valueOf(8190939825036637151l));
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzProductBrandDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzProductBrandDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzProductBrandDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getBzProductBrandDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzProductBrandDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.TrProductStockDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1TrProductStockDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.TrProductStockDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getTrProductStockDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1TrProductStockDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzProductCategoryDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzProductCategorieDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzProductCategoryDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getBzProductCategorieDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzProductCategorieDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzProductAttachmentDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzProductAttachmentDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzProductAttachmentDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getBzProductAttachmentDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzProductAttachmentDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzProductEvaluationDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzProductEvaluationDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzProductEvaluationDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getBzProductEvaluationDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzProductEvaluationDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzInvoiceItemDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzInvoiceItemDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzInvoiceItemDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getBzInvoiceItemDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzInvoiceItemDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzPositionDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzPositionDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzPositionDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getBzPositionDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzPositionDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzCartItemDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzCartDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzCartItemDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getBzCartDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzCartDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzStockOrderItemDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzStockOrderItemDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzStockOrderItemDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getBzStockOrderItemDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzStockOrderItemDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzProductFavoriteDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzProductFavoriteDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzProductFavoriteDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getBzProductFavoriteDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzProductFavoriteDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzOrderItemDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzOrderItemDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzOrderItemDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getBzOrderItemDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzOrderItemDtos);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtos
					.add(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1);
			_saveOrUpdate_dtoBzPositionDto.getBzProductDtos().addAll(
					_saveOrUpdate_dtoBzPositionDtoBzProductDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzUserTakeDeliveryAddressDto> _saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzUserTakeDeliveryAddressDto>();
			itaf.WsUserTakeDeliveryAddressService.BzUserTakeDeliveryAddressDto _saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1 = new itaf.WsUserTakeDeliveryAddressService.BzUserTakeDeliveryAddressDto();
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setId(Long.valueOf(7253493914567963545l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setObjId(Long.valueOf(-6886457818841063850l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setCreatedBy(Long.valueOf(-442337802235378253l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setUpdatedBy(Long.valueOf(8104411397084771860l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setMarkForDelete(Boolean.valueOf(false));
			itaf.WsUserTakeDeliveryAddressService.SysUserDto _saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto = new itaf.WsUserTakeDeliveryAddressService.SysUserDto();
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setId(Long.valueOf(9116373056505019533l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setObjId(Long.valueOf(5471965609130109384l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setCreatedBy(Long.valueOf(-7999452584540791347l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setUpdatedBy(Long.valueOf(-1225645694141051209l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setMarkForDelete(Boolean.valueOf(false));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setUsername("Username1367193450");
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setPassword("Password-602348092");
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setMobile("Mobile-1316221295");
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setType(Long.valueOf(-4454210986392918388l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setEmail("Email-1357795979");
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setNickname("Nickname-1693290775");
			java.util.List<itaf.WsUserTakeDeliveryAddressService.SysRoleDto> _saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDtoSysRoles = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.SysRoleDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.getSysRoles()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDtoSysRoles);
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setSysUserDto(_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto);
			itaf.WsUserTakeDeliveryAddressService.BzPositionDto _saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto = new itaf.WsUserTakeDeliveryAddressService.BzPositionDto();
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.setId(Long.valueOf(-1730121867575843751l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.setObjId(Long.valueOf(-8883822674431342010l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.setCreatedBy(Long.valueOf(-4135800116429119117l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.setUpdatedBy(Long.valueOf(-2095711960951897783l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.setMarkForDelete(Boolean.valueOf(true));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.setX(new java.math.BigDecimal(
							"-1573632293241933865.8618722097484083585"));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.setY(new java.math.BigDecimal(
							"7291688973972017179.7527258709217168710"));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.setZ(new java.math.BigDecimal(
							"1338787739819280270.6733133310560826473"));
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzUserPositionDto> _saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDtoBzUserPositionDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzUserPositionDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.getBzUserPositionDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDtoBzUserPositionDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzUserDeliveryAddressDto> _saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDtoBzUserDeliveryAddresseDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzUserDeliveryAddressDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.getBzUserDeliveryAddresseDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDtoBzUserDeliveryAddresseDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzProductDto> _saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDtoBzProductDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzProductDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.getBzProductDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDtoBzProductDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzUserTakeDeliveryAddressDto> _saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDtoBzUserTakeDeliveryAddresseDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzUserTakeDeliveryAddressDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.getBzUserTakeDeliveryAddresseDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDtoBzUserTakeDeliveryAddresseDtos);
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setBzPositionDto(_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto);
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setAddressTag("AddressTag-409244629");
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setAddress("Address140725321");
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setContactPerson("ContactPerson-657125118");
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setContactNo("ContactNo691589961");
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setPostcode("Postcode-1343773808");
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzOrderDto> _saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzOrders = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzOrderDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.getBzOrders()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzOrders);
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtos
					.add(_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1);
			_saveOrUpdate_dtoBzPositionDto
					.getBzUserTakeDeliveryAddresseDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtos);
			_saveOrUpdate_dto.setBzPositionDto(_saveOrUpdate_dtoBzPositionDto);
			_saveOrUpdate_dto.setAddressTag("AddressTag1392296004");
			_saveOrUpdate_dto.setAddress("Address1156682937");
			_saveOrUpdate_dto.setContactPerson("ContactPerson217697620");
			_saveOrUpdate_dto.setContactNo("ContactNo895352836");
			_saveOrUpdate_dto.setPostcode("Postcode-1228765174");
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzOrderDto> _saveOrUpdate_dtoBzOrders = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzOrderDto>();
			itaf.WsUserTakeDeliveryAddressService.BzOrderDto _saveOrUpdate_dtoBzOrdersVal1 = new itaf.WsUserTakeDeliveryAddressService.BzOrderDto();
			_saveOrUpdate_dtoBzOrdersVal1.setId(Long
					.valueOf(-4936521980214160160l));
			_saveOrUpdate_dtoBzOrdersVal1.setObjId(Long
					.valueOf(3607618715174066352l));
			_saveOrUpdate_dtoBzOrdersVal1.setCreatedBy(Long
					.valueOf(2699412513583197243l));
			_saveOrUpdate_dtoBzOrdersVal1
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzOrdersVal1.setUpdatedBy(Long
					.valueOf(-7058487453432336125l));
			_saveOrUpdate_dtoBzOrdersVal1
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzOrdersVal1.setMarkForDelete(Boolean
					.valueOf(true));
			itaf.WsUserTakeDeliveryAddressService.SysUserDto _saveOrUpdate_dtoBzOrdersVal1SysUserByBzConsumerIdDto = new itaf.WsUserTakeDeliveryAddressService.SysUserDto();
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzConsumerIdDto.setId(Long
					.valueOf(8531123912009265784l));
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzConsumerIdDto.setObjId(Long
					.valueOf(-496677988914981171l));
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzConsumerIdDto
					.setCreatedBy(Long.valueOf(-8620546454993244070l));
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzConsumerIdDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzConsumerIdDto
					.setUpdatedBy(Long.valueOf(-7737876269040427062l));
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzConsumerIdDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzConsumerIdDto
					.setMarkForDelete(Boolean.valueOf(true));
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzConsumerIdDto
					.setUsername("Username1503455077");
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzConsumerIdDto
					.setPassword("Password-1696781740");
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzConsumerIdDto
					.setMobile("Mobile-850770783");
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzConsumerIdDto.setType(Long
					.valueOf(-8173283146620226697l));
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzConsumerIdDto
					.setEmail("Email191770661");
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzConsumerIdDto
					.setNickname("Nickname-1774670039");
			java.util.List<itaf.WsUserTakeDeliveryAddressService.SysRoleDto> _saveOrUpdate_dtoBzOrdersVal1SysUserByBzConsumerIdDtoSysRoles = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.SysRoleDto>();
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzConsumerIdDto
					.getSysRoles()
					.addAll(_saveOrUpdate_dtoBzOrdersVal1SysUserByBzConsumerIdDtoSysRoles);
			_saveOrUpdate_dtoBzOrdersVal1
					.setSysUserByBzConsumerIdDto(_saveOrUpdate_dtoBzOrdersVal1SysUserByBzConsumerIdDto);
			itaf.WsUserTakeDeliveryAddressService.SysUserDto _saveOrUpdate_dtoBzOrdersVal1SysUserByBzMerchantIdDto = new itaf.WsUserTakeDeliveryAddressService.SysUserDto();
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzMerchantIdDto.setId(Long
					.valueOf(2413334888375799908l));
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzMerchantIdDto.setObjId(Long
					.valueOf(-9113659194311774492l));
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzMerchantIdDto
					.setCreatedBy(Long.valueOf(-8120479118604387078l));
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzMerchantIdDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzMerchantIdDto
					.setUpdatedBy(Long.valueOf(-3021519419986084439l));
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzMerchantIdDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.912+08:00"));
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzMerchantIdDto
					.setMarkForDelete(Boolean.valueOf(true));
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzMerchantIdDto
					.setUsername("Username-1084405185");
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzMerchantIdDto
					.setPassword("Password930132046");
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzMerchantIdDto
					.setMobile("Mobile284486275");
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzMerchantIdDto.setType(Long
					.valueOf(-4623715859141813508l));
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzMerchantIdDto
					.setEmail("Email1038108118");
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzMerchantIdDto
					.setNickname("Nickname-1653715239");
			java.util.List<itaf.WsUserTakeDeliveryAddressService.SysRoleDto> _saveOrUpdate_dtoBzOrdersVal1SysUserByBzMerchantIdDtoSysRoles = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.SysRoleDto>();
			_saveOrUpdate_dtoBzOrdersVal1SysUserByBzMerchantIdDto
					.getSysRoles()
					.addAll(_saveOrUpdate_dtoBzOrdersVal1SysUserByBzMerchantIdDtoSysRoles);
			_saveOrUpdate_dtoBzOrdersVal1
					.setSysUserByBzMerchantIdDto(_saveOrUpdate_dtoBzOrdersVal1SysUserByBzMerchantIdDto);
			itaf.WsUserTakeDeliveryAddressService.BzUserTakeDeliveryAddressDto _saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDto = new itaf.WsUserTakeDeliveryAddressService.BzUserTakeDeliveryAddressDto();
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDto
					.setId(Long.valueOf(5428647724206954366l));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDto
					.setObjId(Long.valueOf(3013815770913010126l));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDto
					.setCreatedBy(Long.valueOf(2272903961230563739l));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.928+08:00"));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDto
					.setUpdatedBy(Long.valueOf(818419843418209770l));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.928+08:00"));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDto
					.setMarkForDelete(Boolean.valueOf(false));
			itaf.WsUserTakeDeliveryAddressService.SysUserDto _saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoSysUserDto = new itaf.WsUserTakeDeliveryAddressService.SysUserDto();
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoSysUserDto
					.setId(Long.valueOf(-5170320446312530508l));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoSysUserDto
					.setObjId(Long.valueOf(-5004223795848897595l));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoSysUserDto
					.setCreatedBy(Long.valueOf(-3612661547421613702l));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoSysUserDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.928+08:00"));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoSysUserDto
					.setUpdatedBy(Long.valueOf(-4258560047848241262l));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoSysUserDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.928+08:00"));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoSysUserDto
					.setMarkForDelete(Boolean.valueOf(true));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoSysUserDto
					.setUsername("Username-1385133727");
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoSysUserDto
					.setPassword("Password1816382108");
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoSysUserDto
					.setMobile("Mobile-535434386");
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoSysUserDto
					.setType(Long.valueOf(-3153898289371013430l));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoSysUserDto
					.setEmail("Email2017954734");
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoSysUserDto
					.setNickname("Nickname1233820834");
			java.util.List<itaf.WsUserTakeDeliveryAddressService.SysRoleDto> _saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoSysUserDtoSysRoles = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.SysRoleDto>();
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoSysUserDto
					.getSysRoles()
					.addAll(_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoSysUserDtoSysRoles);
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDto
					.setSysUserDto(_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoSysUserDto);
			itaf.WsUserTakeDeliveryAddressService.BzPositionDto _saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDto = new itaf.WsUserTakeDeliveryAddressService.BzPositionDto();
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDto
					.setId(Long.valueOf(2902149988043199707l));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDto
					.setObjId(Long.valueOf(-5068123858149622864l));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDto
					.setCreatedBy(Long.valueOf(8597964334585583030l));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.928+08:00"));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDto
					.setUpdatedBy(Long.valueOf(8720089794239850152l));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:48:09.928+08:00"));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDto
					.setMarkForDelete(Boolean.valueOf(true));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDto
					.setX(new java.math.BigDecimal(
							"-5872677507045029216.1705530856123055353"));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDto
					.setY(new java.math.BigDecimal(
							"361045754419813460.1495836134001737805"));
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDto
					.setZ(new java.math.BigDecimal(
							"-6430657207696234844.8351051628632580107"));
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzUserPositionDto> _saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDtoBzUserPositionDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzUserPositionDto>();
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDto
					.getBzUserPositionDtos()
					.addAll(_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDtoBzUserPositionDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzUserDeliveryAddressDto> _saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDtoBzUserDeliveryAddresseDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzUserDeliveryAddressDto>();
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDto
					.getBzUserDeliveryAddresseDtos()
					.addAll(_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDtoBzUserDeliveryAddresseDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzProductDto> _saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDtoBzProductDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzProductDto>();
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDto
					.getBzProductDtos()
					.addAll(_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDtoBzProductDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzUserTakeDeliveryAddressDto> _saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDtoBzUserTakeDeliveryAddresseDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzUserTakeDeliveryAddressDto>();
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDto
					.getBzUserTakeDeliveryAddresseDtos()
					.addAll(_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDtoBzUserTakeDeliveryAddresseDtos);
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDto
					.setBzPositionDto(_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzPositionDto);
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDto
					.setAddressTag("AddressTag-1775064978");
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDto
					.setAddress("Address-648202455");
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDto
					.setContactPerson("ContactPerson1629358213");
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDto
					.setContactNo("ContactNo-1220366025");
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDto
					.setPostcode("Postcode1466829135");
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzOrderDto> _saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzOrders = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzOrderDto>();
			_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDto
					.getBzOrders()
					.addAll(_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDtoBzOrders);
			_saveOrUpdate_dtoBzOrdersVal1
					.setBzUserTakeDeliveryAddressDto(_saveOrUpdate_dtoBzOrdersVal1BzUserTakeDeliveryAddressDto);
			_saveOrUpdate_dtoBzOrdersVal1
					.setOrderSerialNo("OrderSerialNo1126513001");
			_saveOrUpdate_dtoBzOrdersVal1.setOrderStatus(Long
					.valueOf(-3385180002084743037l));
			_saveOrUpdate_dtoBzOrdersVal1
					.setOrderDiscount(new java.math.BigDecimal(
							"-3879796912453501057.5303703619165601083"));
			_saveOrUpdate_dtoBzOrdersVal1
					.setOrderPreferential(new java.math.BigDecimal(
							"3825304298349490427.3623271724827281641"));
			_saveOrUpdate_dtoBzOrdersVal1
					.setOrderAmount(new java.math.BigDecimal(
							"8440065424206726151.5465258164148389793"));
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzConsumerCreditEvalDto> _saveOrUpdate_dtoBzOrdersVal1BzConsumerCreditEvalDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzConsumerCreditEvalDto>();
			_saveOrUpdate_dtoBzOrdersVal1.getBzConsumerCreditEvalDtos().addAll(
					_saveOrUpdate_dtoBzOrdersVal1BzConsumerCreditEvalDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzOrderHistoryDto> _saveOrUpdate_dtoBzOrdersVal1BzOrderHistorieDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzOrderHistoryDto>();
			_saveOrUpdate_dtoBzOrdersVal1.getBzOrderHistorieDtos().addAll(
					_saveOrUpdate_dtoBzOrdersVal1BzOrderHistorieDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzDistComCreditEvalDto> _saveOrUpdate_dtoBzOrdersVal1BzDistComCreditEvalDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzDistComCreditEvalDto>();
			_saveOrUpdate_dtoBzOrdersVal1.getBzDistComCreditEvalDtos().addAll(
					_saveOrUpdate_dtoBzOrdersVal1BzDistComCreditEvalDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzOrderPaymentDto> _saveOrUpdate_dtoBzOrdersVal1BzOrderPaymentDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzOrderPaymentDto>();
			_saveOrUpdate_dtoBzOrdersVal1.getBzOrderPaymentDtos().addAll(
					_saveOrUpdate_dtoBzOrdersVal1BzOrderPaymentDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzMerchantCreditEvalDto> _saveOrUpdate_dtoBzOrdersVal1BzMerchantCreditEvalDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzMerchantCreditEvalDto>();
			_saveOrUpdate_dtoBzOrdersVal1.getBzMerchantCreditEvalDtos().addAll(
					_saveOrUpdate_dtoBzOrdersVal1BzMerchantCreditEvalDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzInvoiceDto> _saveOrUpdate_dtoBzOrdersVal1BzInvoiceDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzInvoiceDto>();
			_saveOrUpdate_dtoBzOrdersVal1.getBzInvoiceDtos().addAll(
					_saveOrUpdate_dtoBzOrdersVal1BzInvoiceDtos);
			java.util.List<itaf.WsUserTakeDeliveryAddressService.BzOrderItemDto> _saveOrUpdate_dtoBzOrdersVal1BzOrderItemDtos = new java.util.ArrayList<itaf.WsUserTakeDeliveryAddressService.BzOrderItemDto>();
			_saveOrUpdate_dtoBzOrdersVal1.getBzOrderItemDtos().addAll(
					_saveOrUpdate_dtoBzOrdersVal1BzOrderItemDtos);
			_saveOrUpdate_dtoBzOrders.add(_saveOrUpdate_dtoBzOrdersVal1);
			_saveOrUpdate_dto.getBzOrders().addAll(_saveOrUpdate_dtoBzOrders);
			itaf.WsUserTakeDeliveryAddressService.WsPageResult _saveOrUpdate__return = port
					.saveOrUpdate(_saveOrUpdate_dto);
			System.out.println("saveOrUpdate.result=" + _saveOrUpdate__return);

		}
		{
			System.out.println("Invoking deleteById...");
			java.lang.Long _deleteById_id = Long.valueOf(-3875084697031777078l);
			itaf.WsUserTakeDeliveryAddressService.WsPageResult _deleteById__return = port
					.deleteById(_deleteById_id);
			System.out.println("deleteById.result=" + _deleteById__return);

		}

		System.exit(0);
	}

}
