
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package itaf.WsUserTakeDeliveryAddressService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-25T10:48:09.943+08:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WsUserTakeDeliveryAddressService",
                      portName = "WsUserTakeDeliveryAddressServiceImplPort",
                      targetNamespace = "http://impl.consumer.server.ws.framework.itaf/",
                      wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsUserTakeDeliveryAddressService?wsdl",
                      endpointInterface = "itaf.WsUserTakeDeliveryAddressService.WsUserTakeDeliveryAddressService")
                      
public class WsUserTakeDeliveryAddressServiceImplPortImpl implements WsUserTakeDeliveryAddressService {

    private static final Logger LOG = Logger.getLogger(WsUserTakeDeliveryAddressServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see itaf.WsUserTakeDeliveryAddressService.WsUserTakeDeliveryAddressService#findListByUserId(java.lang.Long  userId )*
     */
    public itaf.WsUserTakeDeliveryAddressService.WsPageResult findListByUserId(java.lang.Long userId) { 
        LOG.info("Executing operation findListByUserId");
        System.out.println(userId);
        try {
            itaf.WsUserTakeDeliveryAddressService.WsPageResult _return = new itaf.WsUserTakeDeliveryAddressService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(738665324);
            _return.setCurrentPage(1684500325);
            _return.setPageSize(45868994);
            _return.setStatus("Status-2069565680");
            _return.setStatusCode("StatusCode681096011");
            _return.setTotalCount(1651937467);
            _return.setTotalPage(-1803648795);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see itaf.WsUserTakeDeliveryAddressService.WsUserTakeDeliveryAddressService#getById(java.lang.Long  id )*
     */
    public itaf.WsUserTakeDeliveryAddressService.WsPageResult getById(java.lang.Long id) { 
        LOG.info("Executing operation getById");
        System.out.println(id);
        try {
            itaf.WsUserTakeDeliveryAddressService.WsPageResult _return = new itaf.WsUserTakeDeliveryAddressService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(-1902764502);
            _return.setCurrentPage(1107463487);
            _return.setPageSize(1701898424);
            _return.setStatus("Status-2100641494");
            _return.setStatusCode("StatusCode-1770236142");
            _return.setTotalCount(-1763147123);
            _return.setTotalPage(885600710);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see itaf.WsUserTakeDeliveryAddressService.WsUserTakeDeliveryAddressService#saveOrUpdate(itaf.WsUserTakeDeliveryAddressService.BzUserTakeDeliveryAddressDto  dto )*
     */
    public itaf.WsUserTakeDeliveryAddressService.WsPageResult saveOrUpdate(itaf.WsUserTakeDeliveryAddressService.BzUserTakeDeliveryAddressDto dto) { 
        LOG.info("Executing operation saveOrUpdate");
        System.out.println(dto);
        try {
            itaf.WsUserTakeDeliveryAddressService.WsPageResult _return = new itaf.WsUserTakeDeliveryAddressService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(846052786);
            _return.setCurrentPage(-1423462189);
            _return.setPageSize(-1074331122);
            _return.setStatus("Status-1030439770");
            _return.setStatusCode("StatusCode-1554196303");
            _return.setTotalCount(537878311);
            _return.setTotalPage(-56829954);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see itaf.WsUserTakeDeliveryAddressService.WsUserTakeDeliveryAddressService#deleteById(java.lang.Long  id )*
     */
    public itaf.WsUserTakeDeliveryAddressService.WsPageResult deleteById(java.lang.Long id) { 
        LOG.info("Executing operation deleteById");
        System.out.println(id);
        try {
            itaf.WsUserTakeDeliveryAddressService.WsPageResult _return = new itaf.WsUserTakeDeliveryAddressService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(-932538952);
            _return.setCurrentPage(165918560);
            _return.setPageSize(1707909985);
            _return.setStatus("Status-1644128493");
            _return.setStatusCode("StatusCode79247994");
            _return.setTotalCount(-1159257288);
            _return.setTotalPage(1826187149);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
