
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package itaf.WsDistributionModelService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-26T14:15:35.718+08:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "wsDistributionModelService",
                      portName = "WsDistributionModelServiceImplPort",
                      targetNamespace = "http://impl.merchant.server.ws.framework.itaf/",
                      wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsDistributionModelService?wsdl",
                      endpointInterface = "itaf.WsDistributionModelService.WsDistributionModelService")
                      
public class WsDistributionModelServiceImplPortImpl implements WsDistributionModelService {

    private static final Logger LOG = Logger.getLogger(WsDistributionModelServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see itaf.WsDistributionModelService.WsDistributionModelService#findList(*
     */
    public itaf.WsDistributionModelService.WsPageResult findList() { 
        LOG.info("Executing operation findList");
        try {
            itaf.WsDistributionModelService.WsPageResult _return = new itaf.WsDistributionModelService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(2042769430);
            _return.setCurrentPage(-1882258956);
            _return.setPageSize(-600607483);
            _return.setStatus("Status1572540907");
            _return.setStatusCode("StatusCode79259939");
            _return.setTotalCount(667895764);
            _return.setTotalPage(984046162);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
