package itaf.WsDistributionModelService;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-26T14:15:35.749+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "itaf.framework.ws.server.merchant", name = "WsDistributionModelService")
@XmlSeeAlso({ObjectFactory.class})
public interface WsDistributionModelService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findList", targetNamespace = "itaf.framework.ws.server.merchant", className = "itaf.WsDistributionModelService.FindList")
    @WebMethod
    @ResponseWrapper(localName = "findListResponse", targetNamespace = "itaf.framework.ws.server.merchant", className = "itaf.WsDistributionModelService.FindListResponse")
    public itaf.WsDistributionModelService.WsPageResult findList();
}
