package itaf.framework.ws.server.certificate.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-10-09T09:54:21.751+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "WsDistributionServiceApplyService", 
                  wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsDistributionServiceApplyService?wsdl",
                  targetNamespace = "http://impl.certificate.server.ws.framework.itaf/") 
public class WsDistributionServiceApplyService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://impl.certificate.server.ws.framework.itaf/", "WsDistributionServiceApplyService");
    public static final QName WsDistributionServiceApplyServiceImplPort = new QName("http://impl.certificate.server.ws.framework.itaf/", "WsDistributionServiceApplyServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/itaf-web-side/service/WsDistributionServiceApplyService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsDistributionServiceApplyService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/itaf-web-side/service/WsDistributionServiceApplyService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsDistributionServiceApplyService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsDistributionServiceApplyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsDistributionServiceApplyService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsDistributionServiceApplyService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsDistributionServiceApplyService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsDistributionServiceApplyService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WsDistributionServiceApplyService
     */
    @WebEndpoint(name = "WsDistributionServiceApplyServiceImplPort")
    public itaf.WsDistributionServiceApplyService.WsDistributionServiceApplyService getWsDistributionServiceApplyServiceImplPort() {
        return super.getPort(WsDistributionServiceApplyServiceImplPort, itaf.WsDistributionServiceApplyService.WsDistributionServiceApplyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsDistributionServiceApplyService
     */
    @WebEndpoint(name = "WsDistributionServiceApplyServiceImplPort")
    public itaf.WsDistributionServiceApplyService.WsDistributionServiceApplyService getWsDistributionServiceApplyServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WsDistributionServiceApplyServiceImplPort, itaf.WsDistributionServiceApplyService.WsDistributionServiceApplyService.class, features);
    }

}
