package itaf.framework.ws.server.certificate.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-10-09T09:43:16.535+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "WsRealnameCertificateService", 
                  wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsRealnameCertificateService?wsdl",
                  targetNamespace = "http://impl.certificate.server.ws.framework.itaf/") 
public class WsRealnameCertificateService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://impl.certificate.server.ws.framework.itaf/", "WsRealnameCertificateService");
    public static final QName WsRealnameCertificateServiceImplPort = new QName("http://impl.certificate.server.ws.framework.itaf/", "WsRealnameCertificateServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/itaf-web-side/service/WsRealnameCertificateService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsRealnameCertificateService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/itaf-web-side/service/WsRealnameCertificateService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsRealnameCertificateService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsRealnameCertificateService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsRealnameCertificateService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsRealnameCertificateService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsRealnameCertificateService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsRealnameCertificateService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WsRealnameCertificateService
     */
    @WebEndpoint(name = "WsRealnameCertificateServiceImplPort")
    public itaf.WsRealnameCertificateService.WsRealnameCertificateService getWsRealnameCertificateServiceImplPort() {
        return super.getPort(WsRealnameCertificateServiceImplPort, itaf.WsRealnameCertificateService.WsRealnameCertificateService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsRealnameCertificateService
     */
    @WebEndpoint(name = "WsRealnameCertificateServiceImplPort")
    public itaf.WsRealnameCertificateService.WsRealnameCertificateService getWsRealnameCertificateServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WsRealnameCertificateServiceImplPort, itaf.WsRealnameCertificateService.WsRealnameCertificateService.class, features);
    }

}
