package itaf.framework.ws.server.certificate.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-28T13:13:59.611+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "WsRealnameCertificateApplyService", 
                  wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsRealnameCertificateApplyService?wsdl",
                  targetNamespace = "http://impl.certificate.server.ws.framework.itaf/") 
public class WsRealnameCertificateApplyService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://impl.certificate.server.ws.framework.itaf/", "WsRealnameCertificateApplyService");
    public static final QName WsRealnameCertificateApplyServiceImplPort = new QName("http://impl.certificate.server.ws.framework.itaf/", "WsRealnameCertificateApplyServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/itaf-web-side/service/WsRealnameCertificateApplyService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsRealnameCertificateApplyService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/itaf-web-side/service/WsRealnameCertificateApplyService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsRealnameCertificateApplyService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsRealnameCertificateApplyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsRealnameCertificateApplyService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsRealnameCertificateApplyService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsRealnameCertificateApplyService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsRealnameCertificateApplyService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WsRealnameCertificateApplyService
     */
    @WebEndpoint(name = "WsRealnameCertificateApplyServiceImplPort")
    public itaf.WsRealnameCertificateApplyService.WsRealnameCertificateApplyService getWsRealnameCertificateApplyServiceImplPort() {
        return super.getPort(WsRealnameCertificateApplyServiceImplPort, itaf.WsRealnameCertificateApplyService.WsRealnameCertificateApplyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsRealnameCertificateApplyService
     */
    @WebEndpoint(name = "WsRealnameCertificateApplyServiceImplPort")
    public itaf.WsRealnameCertificateApplyService.WsRealnameCertificateApplyService getWsRealnameCertificateApplyServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WsRealnameCertificateApplyServiceImplPort, itaf.WsRealnameCertificateApplyService.WsRealnameCertificateApplyService.class, features);
    }

}
