package itaf.framework.ws.server.certificate.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-29T09:53:30.860+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "WsSellingServiceApplyService", 
                  wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsSellingServiceApplyService?wsdl",
                  targetNamespace = "http://impl.certificate.server.ws.framework.itaf/") 
public class WsSellingServiceApplyService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://impl.certificate.server.ws.framework.itaf/", "WsSellingServiceApplyService");
    public static final QName WsSellingServiceApplyServiceImplPort = new QName("http://impl.certificate.server.ws.framework.itaf/", "WsSellingServiceApplyServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/itaf-web-side/service/WsSellingServiceApplyService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsSellingServiceApplyService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/itaf-web-side/service/WsSellingServiceApplyService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsSellingServiceApplyService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsSellingServiceApplyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsSellingServiceApplyService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsSellingServiceApplyService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsSellingServiceApplyService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsSellingServiceApplyService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WsSellingServiceApplyService
     */
    @WebEndpoint(name = "WsSellingServiceApplyServiceImplPort")
    public itaf.WsSellingServiceApplyService.WsSellingServiceApplyService getWsSellingServiceApplyServiceImplPort() {
        return super.getPort(WsSellingServiceApplyServiceImplPort, itaf.WsSellingServiceApplyService.WsSellingServiceApplyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsSellingServiceApplyService
     */
    @WebEndpoint(name = "WsSellingServiceApplyServiceImplPort")
    public itaf.WsSellingServiceApplyService.WsSellingServiceApplyService getWsSellingServiceApplyServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WsSellingServiceApplyServiceImplPort, itaf.WsSellingServiceApplyService.WsSellingServiceApplyService.class, features);
    }

}
