
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package itaf.WsUserDeliveryAddressService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-25T10:49:08.714+08:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WsUserDeliveryAddressService",
                      portName = "WsUserDeliveryAddressServiceImplPort",
                      targetNamespace = "http://impl.merchant.server.ws.framework.itaf/",
                      wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsUserDeliveryAddressService?wsdl",
                      endpointInterface = "itaf.WsUserDeliveryAddressService.WsUserDeliveryAddressService")
                      
public class WsUserDeliveryAddressServiceImplPortImpl implements WsUserDeliveryAddressService {

    private static final Logger LOG = Logger.getLogger(WsUserDeliveryAddressServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see itaf.WsUserDeliveryAddressService.WsUserDeliveryAddressService#getById(java.lang.Long  id )*
     */
    public itaf.WsUserDeliveryAddressService.WsPageResult getById(java.lang.Long id) { 
        LOG.info("Executing operation getById");
        System.out.println(id);
        try {
            itaf.WsUserDeliveryAddressService.WsPageResult _return = new itaf.WsUserDeliveryAddressService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(1873221174);
            _return.setCurrentPage(-1384857921);
            _return.setPageSize(76483449);
            _return.setStatus("Status1895277109");
            _return.setStatusCode("StatusCode-1061390893");
            _return.setTotalCount(-801387741);
            _return.setTotalPage(-2105731041);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see itaf.WsUserDeliveryAddressService.WsUserDeliveryAddressService#saveOrUpdate(itaf.WsUserDeliveryAddressService.BzUserDeliveryAddressDto  dto )*
     */
    public itaf.WsUserDeliveryAddressService.WsPageResult saveOrUpdate(itaf.WsUserDeliveryAddressService.BzUserDeliveryAddressDto dto) { 
        LOG.info("Executing operation saveOrUpdate");
        System.out.println(dto);
        try {
            itaf.WsUserDeliveryAddressService.WsPageResult _return = new itaf.WsUserDeliveryAddressService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(1836602991);
            _return.setCurrentPage(-810148103);
            _return.setPageSize(687543957);
            _return.setStatus("Status-1830281379");
            _return.setStatusCode("StatusCode-1406956110");
            _return.setTotalCount(1938862782);
            _return.setTotalPage(-873184296);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see itaf.WsUserDeliveryAddressService.WsUserDeliveryAddressService#findListByUserId(java.lang.Long  userId )*
     */
    public itaf.WsUserDeliveryAddressService.WsPageResult findListByUserId(java.lang.Long userId) { 
        LOG.info("Executing operation findListByUserId");
        System.out.println(userId);
        try {
            itaf.WsUserDeliveryAddressService.WsPageResult _return = new itaf.WsUserDeliveryAddressService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(-2097640082);
            _return.setCurrentPage(-515233094);
            _return.setPageSize(606498113);
            _return.setStatus("Status-1760212959");
            _return.setStatusCode("StatusCode-415120935");
            _return.setTotalCount(188433106);
            _return.setTotalPage(-152550146);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see itaf.WsUserDeliveryAddressService.WsUserDeliveryAddressService#deleteById(java.lang.Long  id )*
     */
    public itaf.WsUserDeliveryAddressService.WsPageResult deleteById(java.lang.Long id) { 
        LOG.info("Executing operation deleteById");
        System.out.println(id);
        try {
            itaf.WsUserDeliveryAddressService.WsPageResult _return = new itaf.WsUserDeliveryAddressService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(-664782378);
            _return.setCurrentPage(1315516646);
            _return.setPageSize(443257906);
            _return.setStatus("Status-2009519261");
            _return.setStatusCode("StatusCode-2042968168");
            _return.setTotalCount(-812013491);
            _return.setTotalPage(-1775010143);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
