package itaf.WsUserDeliveryAddressService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-25T10:49:08.730+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "itaf.framework.ws.server.merchant", name = "WsUserDeliveryAddressService")
@XmlSeeAlso({ObjectFactory.class})
public interface WsUserDeliveryAddressService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getById", targetNamespace = "itaf.framework.ws.server.merchant", className = "itaf.WsUserDeliveryAddressService.GetById")
    @WebMethod
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "itaf.framework.ws.server.merchant", className = "itaf.WsUserDeliveryAddressService.GetByIdResponse")
    public itaf.WsUserDeliveryAddressService.WsPageResult getById(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveOrUpdate", targetNamespace = "itaf.framework.ws.server.merchant", className = "itaf.WsUserDeliveryAddressService.SaveOrUpdate")
    @WebMethod
    @ResponseWrapper(localName = "saveOrUpdateResponse", targetNamespace = "itaf.framework.ws.server.merchant", className = "itaf.WsUserDeliveryAddressService.SaveOrUpdateResponse")
    public itaf.WsUserDeliveryAddressService.WsPageResult saveOrUpdate(
        @WebParam(name = "dto", targetNamespace = "")
        itaf.WsUserDeliveryAddressService.BzUserDeliveryAddressDto dto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findListByUserId", targetNamespace = "itaf.framework.ws.server.merchant", className = "itaf.WsUserDeliveryAddressService.FindListByUserId")
    @WebMethod
    @ResponseWrapper(localName = "findListByUserIdResponse", targetNamespace = "itaf.framework.ws.server.merchant", className = "itaf.WsUserDeliveryAddressService.FindListByUserIdResponse")
    public itaf.WsUserDeliveryAddressService.WsPageResult findListByUserId(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteById", targetNamespace = "itaf.framework.ws.server.merchant", className = "itaf.WsUserDeliveryAddressService.DeleteById")
    @WebMethod
    @ResponseWrapper(localName = "deleteByIdResponse", targetNamespace = "itaf.framework.ws.server.merchant", className = "itaf.WsUserDeliveryAddressService.DeleteByIdResponse")
    public itaf.WsUserDeliveryAddressService.WsPageResult deleteById(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );
}
