package itaf.WsUserDeliveryAddressService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import itaf.framework.ws.server.merchant.impl.WsUserDeliveryAddressService;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.1 2014-09-25T10:49:08.621+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class WsUserDeliveryAddressService_WsUserDeliveryAddressServiceImplPort_Client {

	private static final QName SERVICE_NAME = new QName(
			"http://impl.merchant.server.ws.framework.itaf/",
			"WsUserDeliveryAddressService");

	private WsUserDeliveryAddressService_WsUserDeliveryAddressServiceImplPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = WsUserDeliveryAddressService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		WsUserDeliveryAddressService ss = new WsUserDeliveryAddressService(
				wsdlURL, SERVICE_NAME);
		itaf.WsUserDeliveryAddressService.WsUserDeliveryAddressService port = ss
				.getWsUserDeliveryAddressServiceImplPort();

		{
			System.out.println("Invoking getById...");
			java.lang.Long _getById_id = Long.valueOf(-5337673467436716447l);
			itaf.WsUserDeliveryAddressService.WsPageResult _getById__return = port
					.getById(_getById_id);
			System.out.println("getById.result=" + _getById__return);

		}
		{
			System.out.println("Invoking saveOrUpdate...");
			itaf.WsUserDeliveryAddressService.BzUserDeliveryAddressDto _saveOrUpdate_dto = new itaf.WsUserDeliveryAddressService.BzUserDeliveryAddressDto();
			_saveOrUpdate_dto.setId(Long.valueOf(4447508534179946117l));
			_saveOrUpdate_dto.setObjId(Long.valueOf(8779893226790818455l));
			_saveOrUpdate_dto.setCreatedBy(Long.valueOf(4771329017867016931l));
			_saveOrUpdate_dto.setCreatedDate(javax.xml.datatype.DatatypeFactory
					.newInstance().newXMLGregorianCalendar(
							"2014-09-25T10:49:08.683+08:00"));
			_saveOrUpdate_dto.setUpdatedBy(Long.valueOf(-4108563602675342878l));
			_saveOrUpdate_dto.setUpdatedDate(javax.xml.datatype.DatatypeFactory
					.newInstance().newXMLGregorianCalendar(
							"2014-09-25T10:49:08.683+08:00"));
			_saveOrUpdate_dto.setMarkForDelete(Boolean.valueOf(true));
			itaf.WsUserDeliveryAddressService.SysUserDto _saveOrUpdate_dtoSysUserDto = new itaf.WsUserDeliveryAddressService.SysUserDto();
			_saveOrUpdate_dtoSysUserDto.setId(Long
					.valueOf(-6334824339075496603l));
			_saveOrUpdate_dtoSysUserDto.setObjId(Long
					.valueOf(-5915278566064055370l));
			_saveOrUpdate_dtoSysUserDto.setCreatedBy(Long
					.valueOf(8457266529289643431l));
			_saveOrUpdate_dtoSysUserDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.683+08:00"));
			_saveOrUpdate_dtoSysUserDto.setUpdatedBy(Long
					.valueOf(-2851419536860606446l));
			_saveOrUpdate_dtoSysUserDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.683+08:00"));
			_saveOrUpdate_dtoSysUserDto.setMarkForDelete(Boolean.valueOf(true));
			_saveOrUpdate_dtoSysUserDto.setUsername("Username-1117182652");
			_saveOrUpdate_dtoSysUserDto.setPassword("Password-1653243686");
			_saveOrUpdate_dtoSysUserDto.setMobile("Mobile-1913904702");
			_saveOrUpdate_dtoSysUserDto.setType(Long
					.valueOf(-7817811482283919275l));
			_saveOrUpdate_dtoSysUserDto.setEmail("Email-2145058708");
			_saveOrUpdate_dtoSysUserDto.setNickname("Nickname-1340227925");
			java.util.List<itaf.WsUserDeliveryAddressService.SysRoleDto> _saveOrUpdate_dtoSysUserDtoSysRoles = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.SysRoleDto>();
			itaf.WsUserDeliveryAddressService.SysRoleDto _saveOrUpdate_dtoSysUserDtoSysRolesVal1 = new itaf.WsUserDeliveryAddressService.SysRoleDto();
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1.setId(Long
					.valueOf(4368654371577876757l));
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1.setObjId(Long
					.valueOf(4076713355837600559l));
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1.setCreatedBy(Long
					.valueOf(-2085645739137508243l));
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.683+08:00"));
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1.setUpdatedBy(Long
					.valueOf(2750109048158849763l));
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.683+08:00"));
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1.setMarkForDelete(Boolean
					.valueOf(false));
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1
					.setNameZh("NameZh1778267082");
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1.setNameEn("NameEn26801231");
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1
					.setDescription("Description1158056069");
			java.util.List<itaf.WsUserDeliveryAddressService.SysResourceDto> _saveOrUpdate_dtoSysUserDtoSysRolesVal1SysResourceDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.SysResourceDto>();
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1
					.getSysResourceDtos()
					.addAll(_saveOrUpdate_dtoSysUserDtoSysRolesVal1SysResourceDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.SysUserDto> _saveOrUpdate_dtoSysUserDtoSysRolesVal1SysUserDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.SysUserDto>();
			_saveOrUpdate_dtoSysUserDtoSysRolesVal1.getSysUserDtos().addAll(
					_saveOrUpdate_dtoSysUserDtoSysRolesVal1SysUserDtos);
			_saveOrUpdate_dtoSysUserDtoSysRoles
					.add(_saveOrUpdate_dtoSysUserDtoSysRolesVal1);
			_saveOrUpdate_dtoSysUserDto.getSysRoles().addAll(
					_saveOrUpdate_dtoSysUserDtoSysRoles);
			_saveOrUpdate_dto.setSysUserDto(_saveOrUpdate_dtoSysUserDto);
			itaf.WsUserDeliveryAddressService.BzPositionDto _saveOrUpdate_dtoBzPositionDto = new itaf.WsUserDeliveryAddressService.BzPositionDto();
			_saveOrUpdate_dtoBzPositionDto.setId(Long
					.valueOf(-1701221418096928714l));
			_saveOrUpdate_dtoBzPositionDto.setObjId(Long
					.valueOf(-8038969641589724884l));
			_saveOrUpdate_dtoBzPositionDto.setCreatedBy(Long
					.valueOf(-4641905580712932698l));
			_saveOrUpdate_dtoBzPositionDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.683+08:00"));
			_saveOrUpdate_dtoBzPositionDto.setUpdatedBy(Long
					.valueOf(5251555299207276225l));
			_saveOrUpdate_dtoBzPositionDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.683+08:00"));
			_saveOrUpdate_dtoBzPositionDto.setMarkForDelete(Boolean
					.valueOf(true));
			_saveOrUpdate_dtoBzPositionDto.setX(new java.math.BigDecimal(
					"2155981292243004368.5426083642024769687"));
			_saveOrUpdate_dtoBzPositionDto.setY(new java.math.BigDecimal(
					"7967109361950878525.8721987943636220822"));
			_saveOrUpdate_dtoBzPositionDto.setZ(new java.math.BigDecimal(
					"-2064477753390734958.7785543708714783033"));
			java.util.List<itaf.WsUserDeliveryAddressService.BzUserPositionDto> _saveOrUpdate_dtoBzPositionDtoBzUserPositionDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzUserPositionDto>();
			itaf.WsUserDeliveryAddressService.BzUserPositionDto _saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1 = new itaf.WsUserDeliveryAddressService.BzUserPositionDto();
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1.setId(Long
					.valueOf(8148626379217302899l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1.setObjId(Long
					.valueOf(6288783339503361013l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1
					.setCreatedBy(Long.valueOf(2985241478638578590l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.683+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1
					.setUpdatedBy(Long.valueOf(544222473618389475l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.683+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1
					.setMarkForDelete(Boolean.valueOf(false));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1
					.setSysUserId(Long.valueOf(8290150748634611715l));
			itaf.WsUserDeliveryAddressService.SysUserDto _saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto = new itaf.WsUserDeliveryAddressService.SysUserDto();
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setId(Long.valueOf(-4228281436724330540l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setObjId(Long.valueOf(1600677956817857037l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setCreatedBy(Long.valueOf(-1095338414184536481l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.683+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setUpdatedBy(Long.valueOf(-4047188996733150139l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.683+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setMarkForDelete(Boolean.valueOf(false));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setUsername("Username-503961305");
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setPassword("Password-2113649343");
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setMobile("Mobile-1250348417");
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setType(Long.valueOf(-2962513272758271632l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setEmail("Email-801005076");
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.setNickname("Nickname1234232488");
			java.util.List<itaf.WsUserDeliveryAddressService.SysRoleDto> _saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDtoSysRoles = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.SysRoleDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto
					.getSysRoles()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDtoSysRoles);
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1
					.setSysUserDto(_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1SysUserDto);
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1
					.setBzPositionId(Long.valueOf(3081919128214738570l));
			itaf.WsUserDeliveryAddressService.BzPositionDto _saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto = new itaf.WsUserDeliveryAddressService.BzPositionDto();
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.setId(Long.valueOf(-3853729210099259146l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.setObjId(Long.valueOf(7623876032294571297l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.setCreatedBy(Long.valueOf(-5713966836423654048l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.683+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.setUpdatedBy(Long.valueOf(5575809554518128595l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.683+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.setMarkForDelete(Boolean.valueOf(false));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.setX(new java.math.BigDecimal(
							"-3877242691915469054.2342015830129159297"));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.setY(new java.math.BigDecimal(
							"-8264808354888658348.7200910472210918635"));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.setZ(new java.math.BigDecimal(
							"6136432260387183104.8200504037386274757"));
			java.util.List<itaf.WsUserDeliveryAddressService.BzUserPositionDto> _saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDtoBzUserPositionDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzUserPositionDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.getBzUserPositionDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDtoBzUserPositionDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzUserDeliveryAddressDto> _saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDtoBzUserDeliveryAddresseDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzUserDeliveryAddressDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.getBzUserDeliveryAddresseDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDtoBzUserDeliveryAddresseDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzProductDto> _saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDtoBzProductDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzProductDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.getBzProductDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDtoBzProductDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzUserTakeDeliveryAddressDto> _saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDtoBzUserTakeDeliveryAddresseDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzUserTakeDeliveryAddressDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto
					.getBzUserTakeDeliveryAddresseDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDtoBzUserTakeDeliveryAddresseDtos);
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1
					.setBzPositionDto(_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1BzPositionDto);
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1
					.setServiceCoverage(Long.valueOf(7709099234466731214l));
			_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtos
					.add(_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtosVal1);
			_saveOrUpdate_dtoBzPositionDto.getBzUserPositionDtos().addAll(
					_saveOrUpdate_dtoBzPositionDtoBzUserPositionDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzUserDeliveryAddressDto> _saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzUserDeliveryAddressDto>();
			itaf.WsUserDeliveryAddressService.BzUserDeliveryAddressDto _saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1 = new itaf.WsUserDeliveryAddressService.BzUserDeliveryAddressDto();
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setId(Long.valueOf(-4455659466960369628l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setObjId(Long.valueOf(-7540857915393619159l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setCreatedBy(Long.valueOf(-150538834712392656l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.699+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setUpdatedBy(Long.valueOf(4700011873696157441l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.699+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setMarkForDelete(Boolean.valueOf(true));
			itaf.WsUserDeliveryAddressService.SysUserDto _saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto = new itaf.WsUserDeliveryAddressService.SysUserDto();
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setId(Long.valueOf(-5610402545689990797l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setObjId(Long.valueOf(-5215900702851522734l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setCreatedBy(Long.valueOf(4891130693952765076l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.699+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setUpdatedBy(Long.valueOf(2754920551398170337l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.699+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setMarkForDelete(Boolean.valueOf(true));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setUsername("Username-1737528674");
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setPassword("Password-497190282");
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setMobile("Mobile-839863391");
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setType(Long.valueOf(-7480303580713456150l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setEmail("Email-430276521");
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.setNickname("Nickname-590275992");
			java.util.List<itaf.WsUserDeliveryAddressService.SysRoleDto> _saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDtoSysRoles = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.SysRoleDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto
					.getSysRoles()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDtoSysRoles);
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setSysUserDto(_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1SysUserDto);
			itaf.WsUserDeliveryAddressService.BzPositionDto _saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto = new itaf.WsUserDeliveryAddressService.BzPositionDto();
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.setId(Long.valueOf(2392031389999109905l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.setObjId(Long.valueOf(-3061473633725890854l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.setCreatedBy(Long.valueOf(-3515259458030949034l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.699+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.setUpdatedBy(Long.valueOf(6384004300272112379l));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.699+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.setMarkForDelete(Boolean.valueOf(true));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.setX(new java.math.BigDecimal(
							"8480175168927245131.1425164955324787377"));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.setY(new java.math.BigDecimal(
							"4548227945950966214.7253285225849330193"));
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.setZ(new java.math.BigDecimal(
							"-9170348775694484604.8744684812078816827"));
			java.util.List<itaf.WsUserDeliveryAddressService.BzUserPositionDto> _saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDtoBzUserPositionDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzUserPositionDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.getBzUserPositionDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDtoBzUserPositionDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzUserDeliveryAddressDto> _saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDtoBzUserDeliveryAddresseDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzUserDeliveryAddressDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.getBzUserDeliveryAddresseDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDtoBzUserDeliveryAddresseDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzProductDto> _saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDtoBzProductDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzProductDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.getBzProductDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDtoBzProductDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzUserTakeDeliveryAddressDto> _saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDtoBzUserTakeDeliveryAddresseDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzUserTakeDeliveryAddressDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto
					.getBzUserTakeDeliveryAddresseDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDtoBzUserTakeDeliveryAddresseDtos);
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setBzPositionDto(_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1BzPositionDto);
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setAddressTag("AddressTag1536610149");
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setAddress("Address-1031682384");
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setContactPerson("ContactPerson-1756776096");
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setContactNo("ContactNo-661379553");
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1
					.setPostcode("Postcode-890300539");
			_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtos
					.add(_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtosVal1);
			_saveOrUpdate_dtoBzPositionDto
					.getBzUserDeliveryAddresseDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserDeliveryAddresseDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzProductDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzProductDto>();
			itaf.WsUserDeliveryAddressService.BzProductDto _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1 = new itaf.WsUserDeliveryAddressService.BzProductDto();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1.setId(Long
					.valueOf(7734094841561358709l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1.setObjId(Long
					.valueOf(-4934263419221368923l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1.setCreatedBy(Long
					.valueOf(1977763031891444016l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.699+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1.setUpdatedBy(Long
					.valueOf(916604325672002437l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.699+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setMarkForDelete(Boolean.valueOf(true));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setBzMerchantId(Long.valueOf(-8055852953900682118l));
			itaf.WsUserDeliveryAddressService.BzMerchantDto _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDto = new itaf.WsUserDeliveryAddressService.BzMerchantDto();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDto
					.setId(Long.valueOf(7460316359497406022l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDto
					.setObjId(Long.valueOf(-5350268617296795291l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDto
					.setCreatedBy(Long.valueOf(-7536659875788534193l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.699+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDto
					.setUpdatedBy(Long.valueOf(-3480970541369037678l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.699+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDto
					.setMarkForDelete(Boolean.valueOf(true));
			itaf.WsUserDeliveryAddressService.BzServiceProviderTypeDto _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto = new itaf.WsUserDeliveryAddressService.BzServiceProviderTypeDto();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setId(Long.valueOf(-802263101858608096l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setObjId(Long.valueOf(-1192559055569743387l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setCreatedBy(Long.valueOf(2034686506663386640l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.699+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setUpdatedBy(Long.valueOf(-4155060295404839814l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.699+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setMarkForDelete(Boolean.valueOf(false));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setParentId(Long.valueOf(-3908444737224064242l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setOrderNo(Long.valueOf(8898317016355741824l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setIsLeaf(Boolean.valueOf(true));
			itaf.WsUserDeliveryAddressService.BzServiceProviderTypeDto _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto = new itaf.WsUserDeliveryAddressService.BzServiceProviderTypeDto();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setId(Long.valueOf(-6152705577002868370l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setObjId(Long.valueOf(-2590204373692214742l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setCreatedBy(Long.valueOf(129754905388580900l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.699+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setUpdatedBy(Long.valueOf(-544550314228280809l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.699+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setMarkForDelete(Boolean.valueOf(true));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setParentId(Long.valueOf(-5383521006308824857l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setOrderNo(Long.valueOf(-755660916625596078l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setIsLeaf(Boolean.valueOf(false));
			itaf.WsUserDeliveryAddressService.BzServiceProviderTypeDto _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto = new itaf.WsUserDeliveryAddressService.BzServiceProviderTypeDto();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setId(Long.valueOf(-1987446172514308027l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setObjId(Long.valueOf(1101839577998547124l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setCreatedBy(Long.valueOf(-6335878477545333397l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.699+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setUpdatedBy(Long.valueOf(4121132043685869097l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.699+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setMarkForDelete(Boolean.valueOf(false));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setParentId(Long.valueOf(3006477576154824818l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setOrderNo(Long.valueOf(-748452422830376748l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setIsLeaf(Boolean.valueOf(false));
			itaf.WsUserDeliveryAddressService.BzServiceProviderTypeDto _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto = new itaf.WsUserDeliveryAddressService.BzServiceProviderTypeDto();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setId(Long.valueOf(-3510992782100120128l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setObjId(Long.valueOf(-5457312555344192416l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setCreatedBy(Long.valueOf(6786468072108978925l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.699+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setUpdatedBy(Long.valueOf(-611926161518102208l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.699+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setMarkForDelete(Boolean.valueOf(true));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setParentId(Long.valueOf(2319563917681040618l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setOrderNo(Long.valueOf(6037464806257413655l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setIsLeaf(Boolean.valueOf(false));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setParentDto(null);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setTypeName("TypeName402855296");
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.setTypeCode("TypeCode1256705526");
			java.util.List<itaf.WsUserDeliveryAddressService.BzServiceProviderTypeDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDtoChildrenDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzServiceProviderTypeDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.getChildrenDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDtoChildrenDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzDistributionCompanyDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDtoBzDistributionCompanieDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzDistributionCompanyDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.getBzDistributionCompanieDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDtoBzDistributionCompanieDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzMerchantDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDtoBzMerchantDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzMerchantDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto
					.getBzMerchantDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDtoBzMerchantDtos);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setParentDto(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoParentDto);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setTypeName("TypeName599455186");
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.setTypeCode("TypeCode1980003638");
			java.util.List<itaf.WsUserDeliveryAddressService.BzServiceProviderTypeDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoChildrenDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzServiceProviderTypeDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.getChildrenDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoChildrenDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzDistributionCompanyDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoBzDistributionCompanieDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzDistributionCompanyDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.getBzDistributionCompanieDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoBzDistributionCompanieDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzMerchantDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoBzMerchantDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzMerchantDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto
					.getBzMerchantDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDtoBzMerchantDtos);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setParentDto(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoParentDto);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setTypeName("TypeName1877000475");
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.setTypeCode("TypeCode108392712");
			java.util.List<itaf.WsUserDeliveryAddressService.BzServiceProviderTypeDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoChildrenDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzServiceProviderTypeDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.getChildrenDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoChildrenDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzDistributionCompanyDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoBzDistributionCompanieDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzDistributionCompanyDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.getBzDistributionCompanieDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoBzDistributionCompanieDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzMerchantDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoBzMerchantDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzMerchantDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto
					.getBzMerchantDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDtoBzMerchantDtos);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setParentDto(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoParentDto);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setTypeName("TypeName-1667033435");
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.setTypeCode("TypeCode-1685954002");
			java.util.List<itaf.WsUserDeliveryAddressService.BzServiceProviderTypeDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoChildrenDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzServiceProviderTypeDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.getChildrenDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoChildrenDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzDistributionCompanyDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoBzDistributionCompanieDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzDistributionCompanyDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.getBzDistributionCompanieDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoBzDistributionCompanieDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzMerchantDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoBzMerchantDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzMerchantDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto
					.getBzMerchantDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDtoBzMerchantDtos);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDto
					.setBzServiceProviderTypeDto(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDtoBzServiceProviderTypeDto);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setBzMerchantDto(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzMerchantDto);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setProductName("ProductName1391763637");
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setProductPrice(new java.math.BigDecimal(
							"8040757421804343182.9044431653888274065"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setProductPurchasePrice(new java.math.BigDecimal(
							"-2618091119636647074.7773604469756886268"));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setProductColor("ProductColor-816071021");
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setProductDescription("ProductDescription-1953691200");
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setProductOnSale(Long.valueOf(3904785139311275072l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setIsStockLimitless(Long.valueOf(645413630720728185l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setIsShelfLimitless(Long.valueOf(2131337097056133171l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setIsStockSupport(Long.valueOf(7345782592361862384l));
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.setIsShelfSupport(Long.valueOf(-1871625494610373365l));
			java.util.List<itaf.WsUserDeliveryAddressService.BzProductBrandDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzProductBrandDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzProductBrandDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getBzProductBrandDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzProductBrandDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.TrProductStockDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1TrProductStockDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.TrProductStockDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getTrProductStockDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1TrProductStockDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzProductCategoryDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzProductCategorieDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzProductCategoryDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getBzProductCategorieDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzProductCategorieDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzProductAttachmentDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzProductAttachmentDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzProductAttachmentDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getBzProductAttachmentDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzProductAttachmentDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzProductEvaluationDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzProductEvaluationDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzProductEvaluationDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getBzProductEvaluationDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzProductEvaluationDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzInvoiceItemDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzInvoiceItemDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzInvoiceItemDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getBzInvoiceItemDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzInvoiceItemDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzPositionDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzPositionDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzPositionDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getBzPositionDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzPositionDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzCartItemDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzCartDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzCartItemDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getBzCartDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzCartDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzStockOrderItemDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzStockOrderItemDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzStockOrderItemDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getBzStockOrderItemDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzStockOrderItemDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzProductFavoriteDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzProductFavoriteDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzProductFavoriteDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getBzProductFavoriteDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzProductFavoriteDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzOrderItemDto> _saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzOrderItemDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzOrderItemDto>();
			_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1
					.getBzOrderItemDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1BzOrderItemDtos);
			_saveOrUpdate_dtoBzPositionDtoBzProductDtos
					.add(_saveOrUpdate_dtoBzPositionDtoBzProductDtosVal1);
			_saveOrUpdate_dtoBzPositionDto.getBzProductDtos().addAll(
					_saveOrUpdate_dtoBzPositionDtoBzProductDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzUserTakeDeliveryAddressDto> _saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzUserTakeDeliveryAddressDto>();
			itaf.WsUserDeliveryAddressService.BzUserTakeDeliveryAddressDto _saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1 = new itaf.WsUserDeliveryAddressService.BzUserTakeDeliveryAddressDto();
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setId(Long.valueOf(-8552437584554906127l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setObjId(Long.valueOf(-4225759618813914214l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setCreatedBy(Long.valueOf(-2342796885198946899l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.699+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setUpdatedBy(Long.valueOf(1823623127141758196l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.699+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setMarkForDelete(Boolean.valueOf(true));
			itaf.WsUserDeliveryAddressService.SysUserDto _saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto = new itaf.WsUserDeliveryAddressService.SysUserDto();
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setId(Long.valueOf(6097975072088573019l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setObjId(Long.valueOf(-6615088203353832296l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setCreatedBy(Long.valueOf(8990215126892067730l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.714+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setUpdatedBy(Long.valueOf(9173035564750072877l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.714+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setMarkForDelete(Boolean.valueOf(true));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setUsername("Username-1923883032");
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setPassword("Password-227855382");
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setMobile("Mobile1758563303");
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setType(Long.valueOf(-8774594190368165821l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setEmail("Email-133665320");
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.setNickname("Nickname1318627589");
			java.util.List<itaf.WsUserDeliveryAddressService.SysRoleDto> _saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDtoSysRoles = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.SysRoleDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto
					.getSysRoles()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDtoSysRoles);
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setSysUserDto(_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1SysUserDto);
			itaf.WsUserDeliveryAddressService.BzPositionDto _saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto = new itaf.WsUserDeliveryAddressService.BzPositionDto();
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.setId(Long.valueOf(1431655750435063729l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.setObjId(Long.valueOf(-2482344556060975778l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.setCreatedBy(Long.valueOf(-7370016085714915174l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.714+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.setUpdatedBy(Long.valueOf(2231597162698375095l));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-09-25T10:49:08.714+08:00"));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.setMarkForDelete(Boolean.valueOf(true));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.setX(new java.math.BigDecimal(
							"4028812040791850684.9086578119051701333"));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.setY(new java.math.BigDecimal(
							"-5576037718435540018.4457938162313407320"));
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.setZ(new java.math.BigDecimal(
							"-8132409237981821058.3824403020243856373"));
			java.util.List<itaf.WsUserDeliveryAddressService.BzUserPositionDto> _saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDtoBzUserPositionDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzUserPositionDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.getBzUserPositionDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDtoBzUserPositionDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzUserDeliveryAddressDto> _saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDtoBzUserDeliveryAddresseDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzUserDeliveryAddressDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.getBzUserDeliveryAddresseDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDtoBzUserDeliveryAddresseDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzProductDto> _saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDtoBzProductDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzProductDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.getBzProductDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDtoBzProductDtos);
			java.util.List<itaf.WsUserDeliveryAddressService.BzUserTakeDeliveryAddressDto> _saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDtoBzUserTakeDeliveryAddresseDtos = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzUserTakeDeliveryAddressDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto
					.getBzUserTakeDeliveryAddresseDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDtoBzUserTakeDeliveryAddresseDtos);
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setBzPositionDto(_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzPositionDto);
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setAddressTag("AddressTag-1399222010");
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setAddress("Address1797675187");
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setContactPerson("ContactPerson1794178144");
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setContactNo("ContactNo-383144504");
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.setPostcode("Postcode-1803233120");
			java.util.List<itaf.WsUserDeliveryAddressService.BzOrderDto> _saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzOrders = new java.util.ArrayList<itaf.WsUserDeliveryAddressService.BzOrderDto>();
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1
					.getBzOrders()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1BzOrders);
			_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtos
					.add(_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtosVal1);
			_saveOrUpdate_dtoBzPositionDto
					.getBzUserTakeDeliveryAddresseDtos()
					.addAll(_saveOrUpdate_dtoBzPositionDtoBzUserTakeDeliveryAddresseDtos);
			_saveOrUpdate_dto.setBzPositionDto(_saveOrUpdate_dtoBzPositionDto);
			_saveOrUpdate_dto.setAddressTag("AddressTag1178037027");
			_saveOrUpdate_dto.setAddress("Address1717011253");
			_saveOrUpdate_dto.setContactPerson("ContactPerson380982638");
			_saveOrUpdate_dto.setContactNo("ContactNo899596163");
			_saveOrUpdate_dto.setPostcode("Postcode-225501706");
			itaf.WsUserDeliveryAddressService.WsPageResult _saveOrUpdate__return = port
					.saveOrUpdate(_saveOrUpdate_dto);
			System.out.println("saveOrUpdate.result=" + _saveOrUpdate__return);

		}
		{
			System.out.println("Invoking findListByUserId...");
			java.lang.Long _findListByUserId_userId = Long
					.valueOf(-4328970787013626222l);
			itaf.WsUserDeliveryAddressService.WsPageResult _findListByUserId__return = port
					.findListByUserId(_findListByUserId_userId);
			System.out.println("findListByUserId.result="
					+ _findListByUserId__return);

		}
		{
			System.out.println("Invoking deleteById...");
			java.lang.Long _deleteById_id = Long.valueOf(3780154262933612713l);
			itaf.WsUserDeliveryAddressService.WsPageResult _deleteById__return = port
					.deleteById(_deleteById_id);
			System.out.println("deleteById.result=" + _deleteById__return);

		}

		System.exit(0);
	}

}
