package itaf.framework.ws.server.platform.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-23T11:04:17.678+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "WsLogoutService", 
                  wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsLogoutService?wsdl",
                  targetNamespace = "http://impl.platform.server.ws.framework.itaf/") 
public class WsLogoutService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://impl.platform.server.ws.framework.itaf/", "WsLogoutService");
    public static final QName WsLogoutServiceImplPort = new QName("http://impl.platform.server.ws.framework.itaf/", "WsLogoutServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/itaf-web-side/service/WsLogoutService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsLogoutService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/itaf-web-side/service/WsLogoutService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsLogoutService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsLogoutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsLogoutService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsLogoutService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsLogoutService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsLogoutService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WsLogoutService
     */
    @WebEndpoint(name = "WsLogoutServiceImplPort")
    public itaf.WsLogoutService.WsLogoutService getWsLogoutServiceImplPort() {
        return super.getPort(WsLogoutServiceImplPort, itaf.WsLogoutService.WsLogoutService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsLogoutService
     */
    @WebEndpoint(name = "WsLogoutServiceImplPort")
    public itaf.WsLogoutService.WsLogoutService getWsLogoutServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WsLogoutServiceImplPort, itaf.WsLogoutService.WsLogoutService.class, features);
    }

}
