package itaf.framework.ws.server.platform.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-23T17:07:50.700+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "WsSysUserService", 
                  wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsSysUserService?wsdl",
                  targetNamespace = "http://impl.platform.server.ws.framework.itaf/") 
public class WsSysUserService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://impl.platform.server.ws.framework.itaf/", "WsSysUserService");
    public static final QName WsSysUserServiceImplPort = new QName("http://impl.platform.server.ws.framework.itaf/", "WsSysUserServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/itaf-web-side/service/WsSysUserService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsSysUserService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/itaf-web-side/service/WsSysUserService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsSysUserService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsSysUserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsSysUserService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsSysUserService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsSysUserService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsSysUserService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WsSysUserService
     */
    @WebEndpoint(name = "WsSysUserServiceImplPort")
    public itaf.WsSysUserService.WsSysUserService getWsSysUserServiceImplPort() {
        return super.getPort(WsSysUserServiceImplPort, itaf.WsSysUserService.WsSysUserService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsSysUserService
     */
    @WebEndpoint(name = "WsSysUserServiceImplPort")
    public itaf.WsSysUserService.WsSysUserService getWsSysUserServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WsSysUserServiceImplPort, itaf.WsSysUserService.WsSysUserService.class, features);
    }

}
