package itaf.framework.ws.server.platform.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-23T14:18:19.562+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "WsSysLoginService", 
                  wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsSysLoginService?wsdl",
                  targetNamespace = "http://impl.platform.server.ws.framework.itaf/") 
public class WsSysLoginService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://impl.platform.server.ws.framework.itaf/", "WsSysLoginService");
    public static final QName WsSysLoginServiceImplPort = new QName("http://impl.platform.server.ws.framework.itaf/", "WsSysLoginServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/itaf-web-side/service/WsSysLoginService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsSysLoginService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/itaf-web-side/service/WsSysLoginService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsSysLoginService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsSysLoginService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsSysLoginService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsSysLoginService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsSysLoginService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsSysLoginService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WsSysLoginService
     */
    @WebEndpoint(name = "WsSysLoginServiceImplPort")
    public itaf.WsSysLoginService.WsSysLoginService getWsSysLoginServiceImplPort() {
        return super.getPort(WsSysLoginServiceImplPort, itaf.WsSysLoginService.WsSysLoginService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsSysLoginService
     */
    @WebEndpoint(name = "WsSysLoginServiceImplPort")
    public itaf.WsSysLoginService.WsSysLoginService getWsSysLoginServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WsSysLoginServiceImplPort, itaf.WsSysLoginService.WsSysLoginService.class, features);
    }

}
