
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package itaf.WsSysLoginService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-23T14:18:19.547+08:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WsSysLoginService",
                      portName = "WsSysLoginServiceImplPort",
                      targetNamespace = "http://impl.platform.server.ws.framework.itaf/",
                      wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsSysLoginService?wsdl",
                      endpointInterface = "itaf.WsSysLoginService.WsSysLoginService")
                      
public class WsSysLoginServiceImplPortImpl implements WsSysLoginService {

    private static final Logger LOG = Logger.getLogger(WsSysLoginServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see itaf.WsSysLoginService.WsSysLoginService#login(java.lang.String  username ,)java.lang.String  password ,)java.lang.String  mobile )*
     */
    public itaf.WsSysLoginService.WsPageResult login(java.lang.String username,java.lang.String password,java.lang.String mobile) { 
        LOG.info("Executing operation login");
        System.out.println(username);
        System.out.println(password);
        System.out.println(mobile);
        try {
            itaf.WsSysLoginService.WsPageResult _return = new itaf.WsSysLoginService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(-1213985855);
            _return.setCurrentPage(-218253942);
            _return.setPageSize(-68648362);
            _return.setStatus("Status-1109510776");
            _return.setStatusCode("StatusCode-676526055");
            _return.setTotalCount(160824500);
            _return.setTotalPage(1243055457);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
