
package itaf.WsSysLoginService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import itaf.framework.ws.server.platform.impl.WsSysLoginService;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-23T14:18:19.484+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class WsSysLoginService_WsSysLoginServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.platform.server.ws.framework.itaf/", "WsSysLoginService");

    private WsSysLoginService_WsSysLoginServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WsSysLoginService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WsSysLoginService ss = new WsSysLoginService(wsdlURL, SERVICE_NAME);
        itaf.WsSysLoginService.WsSysLoginService port = ss.getWsSysLoginServiceImplPort();  
        
        {
        System.out.println("Invoking login...");
        java.lang.String _login_username = "admin";
        java.lang.String _login_password = "1234";
        java.lang.String _login_mobile = "1234";
        itaf.WsSysLoginService.WsPageResult _login__return = port.login(_login_username, _login_password, _login_mobile);
        System.out.println("login.result=" + _login__return);


        }

        System.exit(0);
    }

}
