package itaf.framework.ws.server.cart.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-19T10:49:22.787+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "WsCartItemService", 
                  wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsCartItemService?wsdl",
                  targetNamespace = "http://impl.cart.server.ws.framework.itaf/") 
public class WsCartItemService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://impl.cart.server.ws.framework.itaf/", "WsCartItemService");
    public static final QName WsCartItemServiceImplPort = new QName("http://impl.cart.server.ws.framework.itaf/", "WsCartItemServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/itaf-web-side/service/WsCartItemService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsCartItemService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/itaf-web-side/service/WsCartItemService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsCartItemService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsCartItemService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsCartItemService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsCartItemService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsCartItemService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsCartItemService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WsCartItemService
     */
    @WebEndpoint(name = "WsCartItemServiceImplPort")
    public itaf.WsCartItemService.WsCartItemService getWsCartItemServiceImplPort() {
        return super.getPort(WsCartItemServiceImplPort, itaf.WsCartItemService.WsCartItemService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsCartItemService
     */
    @WebEndpoint(name = "WsCartItemServiceImplPort")
    public itaf.WsCartItemService.WsCartItemService getWsCartItemServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WsCartItemServiceImplPort, itaf.WsCartItemService.WsCartItemService.class, features);
    }

}
