
package itaf.WsSellingServiceApplyService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import itaf.framework.ws.server.certificate.impl.WsSellingServiceApplyService;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-29T09:53:30.673+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class WsSellingServiceApplyService_WsSellingServiceApplyServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.certificate.server.ws.framework.itaf/", "WsSellingServiceApplyService");

    private WsSellingServiceApplyService_WsSellingServiceApplyServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WsSellingServiceApplyService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WsSellingServiceApplyService ss = new WsSellingServiceApplyService(wsdlURL, SERVICE_NAME);
        itaf.WsSellingServiceApplyService.WsSellingServiceApplyService port = ss.getWsSellingServiceApplyServiceImplPort();  
        
        /*{
        System.out.println("Invoking create...");
        itaf.WsSellingServiceApplyService.BzSellingServiceApplyDto _create_dto = new itaf.WsSellingServiceApplyService.BzSellingServiceApplyDto();
        _create_dto.setId(Long.valueOf(-5268073627869587262l));
        _create_dto.setObjId(Long.valueOf(2366414480978742770l));
        _create_dto.setCreatedBy(Long.valueOf(5887625094923671685l));
        _create_dto.setCreatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-29T09:53:30.751+08:00"));
        _create_dto.setUpdatedBy(Long.valueOf(-6668415220101439645l));
        _create_dto.setUpdatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-29T09:53:30.798+08:00"));
        _create_dto.setMarkForDelete(Boolean.valueOf(true));
        itaf.WsSellingServiceApplyService.SysUserDto _create_dtoSysUserDto = new itaf.WsSellingServiceApplyService.SysUserDto();
        _create_dtoSysUserDto.setId(Long.valueOf(1l));
        _create_dtoSysUserDto.setObjId(Long.valueOf(1l));
        _create_dtoSysUserDto.setCreatedBy(Long.valueOf(2678397173300497856l));
        _create_dtoSysUserDto.setCreatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-29T09:53:30.798+08:00"));
        _create_dtoSysUserDto.setUpdatedBy(Long.valueOf(7971018874275276384l));
        _create_dtoSysUserDto.setUpdatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-29T09:53:30.814+08:00"));
        _create_dtoSysUserDto.setMarkForDelete(Boolean.valueOf(false));
        _create_dtoSysUserDto.setUsername("Username2141701984");
        _create_dtoSysUserDto.setPassword("Password-195301473");
        _create_dtoSysUserDto.setMobile("Mobile-259592751");
        _create_dtoSysUserDto.setType(Long.valueOf(-7882735389070886922l));
        _create_dtoSysUserDto.setEmail("Email1452155225");
        _create_dtoSysUserDto.setNickname("Nickname2025859729");
        java.util.List<itaf.WsSellingServiceApplyService.SysRoleDto> _create_dtoSysUserDtoSysRoles = new java.util.ArrayList<itaf.WsSellingServiceApplyService.SysRoleDto>();
        itaf.WsSellingServiceApplyService.SysRoleDto _create_dtoSysUserDtoSysRolesVal1 = new itaf.WsSellingServiceApplyService.SysRoleDto();
        _create_dtoSysUserDtoSysRolesVal1.setId(Long.valueOf(-3184943093672493995l));
        _create_dtoSysUserDtoSysRolesVal1.setObjId(Long.valueOf(-1781124272361078232l));
        _create_dtoSysUserDtoSysRolesVal1.setCreatedBy(Long.valueOf(-6200995681847461088l));
        _create_dtoSysUserDtoSysRolesVal1.setCreatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-29T09:53:30.814+08:00"));
        _create_dtoSysUserDtoSysRolesVal1.setUpdatedBy(Long.valueOf(4220180786447096162l));
        _create_dtoSysUserDtoSysRolesVal1.setUpdatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-29T09:53:30.814+08:00"));
        _create_dtoSysUserDtoSysRolesVal1.setMarkForDelete(Boolean.valueOf(false));
        _create_dtoSysUserDtoSysRolesVal1.setNameZh("NameZh-1108636344");
        _create_dtoSysUserDtoSysRolesVal1.setNameEn("NameEn-507171266");
        _create_dtoSysUserDtoSysRolesVal1.setDescription("Description1503697527");
        java.util.List<itaf.WsSellingServiceApplyService.SysResourceDto> _create_dtoSysUserDtoSysRolesVal1SysResourceDtos = new java.util.ArrayList<itaf.WsSellingServiceApplyService.SysResourceDto>();
        _create_dtoSysUserDtoSysRolesVal1.getSysResourceDtos().addAll(_create_dtoSysUserDtoSysRolesVal1SysResourceDtos);
        java.util.List<itaf.WsSellingServiceApplyService.SysUserDto> _create_dtoSysUserDtoSysRolesVal1SysUserDtos = new java.util.ArrayList<itaf.WsSellingServiceApplyService.SysUserDto>();
        _create_dtoSysUserDtoSysRolesVal1.getSysUserDtos().addAll(_create_dtoSysUserDtoSysRolesVal1SysUserDtos);
        _create_dtoSysUserDtoSysRoles.add(_create_dtoSysUserDtoSysRolesVal1);
        _create_dtoSysUserDto.getSysRoles().addAll(_create_dtoSysUserDtoSysRoles);
        _create_dto.setSysUserDto(_create_dtoSysUserDto);
        _create_dto.setBzAttachmentId(Long.valueOf(-1110119147716728110l));
        _create_dto.setCompanyName("1");
        _create_dto.setCompanyAddress("1");
        _create_dto.setApprovalStatus(Long.valueOf(7544597614563319773l));
        _create_dto.setBzWorkflowId(Long.valueOf(-5985189709667001673l));
        java.util.List<itaf.WsSellingServiceApplyService.BzMerchantCertificateDto> _create_dtoBzMerchantCertificateDtos = new java.util.ArrayList<itaf.WsSellingServiceApplyService.BzMerchantCertificateDto>();
        itaf.WsSellingServiceApplyService.BzMerchantCertificateDto _create_dtoBzMerchantCertificateDtosVal1 = new itaf.WsSellingServiceApplyService.BzMerchantCertificateDto();
        _create_dtoBzMerchantCertificateDtosVal1.setId(Long.valueOf(1687715033439997411l));
        _create_dtoBzMerchantCertificateDtosVal1.setObjId(Long.valueOf(2157507294626857001l));
        _create_dtoBzMerchantCertificateDtosVal1.setCreatedBy(Long.valueOf(121673052951231806l));
        _create_dtoBzMerchantCertificateDtosVal1.setCreatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-29T09:53:30.814+08:00"));
        _create_dtoBzMerchantCertificateDtosVal1.setUpdatedBy(Long.valueOf(-5262600793294020600l));
        _create_dtoBzMerchantCertificateDtosVal1.setUpdatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-29T09:53:30.814+08:00"));
        _create_dtoBzMerchantCertificateDtosVal1.setMarkForDelete(Boolean.valueOf(false));
        itaf.WsSellingServiceApplyService.BzDistServiceApplyDto _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto = new itaf.WsSellingServiceApplyService.BzDistServiceApplyDto();
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto.setId(Long.valueOf(8943237289304591172l));
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto.setObjId(Long.valueOf(4616975195978573558l));
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto.setCreatedBy(Long.valueOf(-8282402729629506158l));
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto.setCreatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-29T09:53:30.814+08:00"));
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto.setUpdatedBy(Long.valueOf(1194229238692688422l));
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto.setUpdatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-29T09:53:30.814+08:00"));
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto.setMarkForDelete(Boolean.valueOf(true));
        itaf.WsSellingServiceApplyService.SysUserDto _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto = new itaf.WsSellingServiceApplyService.SysUserDto();
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto.setId(Long.valueOf(1303155664119227685l));
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto.setObjId(Long.valueOf(2059787376402516381l));
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto.setCreatedBy(Long.valueOf(-1391471361752523004l));
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto.setCreatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-29T09:53:30.814+08:00"));
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto.setUpdatedBy(Long.valueOf(3067761889304174386l));
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto.setUpdatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-29T09:53:30.814+08:00"));
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto.setMarkForDelete(Boolean.valueOf(false));
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto.setUsername("Username-1787304624");
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto.setPassword("Password435429394");
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto.setMobile("Mobile-472048383");
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto.setType(Long.valueOf(-3374539590474169055l));
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto.setEmail("Email-1650024543");
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto.setNickname("Nickname-19717386");
        java.util.List<itaf.WsSellingServiceApplyService.SysRoleDto> _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDtoSysRoles = new java.util.ArrayList<itaf.WsSellingServiceApplyService.SysRoleDto>();
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto.getSysRoles().addAll(_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDtoSysRoles);
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto.setSysUserDto(_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto);
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto.setBzAttachmentId(Long.valueOf(-6039859197192351480l));
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto.setCompanyName("CompanyName-2091090441");
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto.setDistServiceType(Long.valueOf(-5803612707925581183l));
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto.setDistServiceCoverage(Long.valueOf(8168080765883881054l));
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto.setApprovalStatus(Long.valueOf(8991905905134509007l));
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto.setBzWorkflowId(Long.valueOf(1854242509804674785l));
        java.util.List<itaf.WsSellingServiceApplyService.BzMerchantCertificateDto> _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoBzMerchantCertificateDtos = new java.util.ArrayList<itaf.WsSellingServiceApplyService.BzMerchantCertificateDto>();
        _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto.getBzMerchantCertificateDtos().addAll(_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoBzMerchantCertificateDtos);
        _create_dtoBzMerchantCertificateDtosVal1.setBzDistServiceApplyDto(_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto);
        itaf.WsSellingServiceApplyService.BzSellingServiceApplyDto _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto = new itaf.WsSellingServiceApplyService.BzSellingServiceApplyDto();
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto.setId(Long.valueOf(-4332234350921933800l));
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto.setObjId(Long.valueOf(4378519726848019231l));
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto.setCreatedBy(Long.valueOf(-4405189386736316878l));
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto.setCreatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-29T09:53:30.814+08:00"));
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto.setUpdatedBy(Long.valueOf(4044754465827670113l));
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto.setUpdatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-29T09:53:30.814+08:00"));
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto.setMarkForDelete(Boolean.valueOf(false));
        itaf.WsSellingServiceApplyService.SysUserDto _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto = new itaf.WsSellingServiceApplyService.SysUserDto();
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto.setId(Long.valueOf(-656716448251591034l));
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto.setObjId(Long.valueOf(-8617032130505642727l));
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto.setCreatedBy(Long.valueOf(-3278623561380575791l));
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto.setCreatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-29T09:53:30.814+08:00"));
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto.setUpdatedBy(Long.valueOf(-218278764209714179l));
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto.setUpdatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-29T09:53:30.814+08:00"));
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto.setMarkForDelete(Boolean.valueOf(true));
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto.setUsername("Username82904929");
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto.setPassword("Password-1180463954");
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto.setMobile("Mobile518837825");
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto.setType(Long.valueOf(5434915566826583942l));
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto.setEmail("Email-817028910");
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto.setNickname("Nickname104246374");
        java.util.List<itaf.WsSellingServiceApplyService.SysRoleDto> _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDtoSysRoles = new java.util.ArrayList<itaf.WsSellingServiceApplyService.SysRoleDto>();
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto.getSysRoles().addAll(_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDtoSysRoles);
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto.setSysUserDto(_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto);
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto.setBzAttachmentId(Long.valueOf(-2808249558615565492l));
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto.setCompanyName("CompanyName-95469681");
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto.setCompanyAddress("CompanyAddress-1073276467");
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto.setApprovalStatus(Long.valueOf(5559768108035045855l));
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto.setBzWorkflowId(Long.valueOf(627403086689662657l));
        java.util.List<itaf.WsSellingServiceApplyService.BzMerchantCertificateDto> _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoBzMerchantCertificateDtos = new java.util.ArrayList<itaf.WsSellingServiceApplyService.BzMerchantCertificateDto>();
        _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto.getBzMerchantCertificateDtos().addAll(_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoBzMerchantCertificateDtos);
        _create_dtoBzMerchantCertificateDtosVal1.setBzSellingServiceApplyDto(_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto);
        _create_dtoBzMerchantCertificateDtosVal1.setSysUserId(Long.valueOf(-1810618967205414869l));
        _create_dtoBzMerchantCertificateDtosVal1.setCertificateType(Long.valueOf(2401220807097394875l));
        _create_dtoBzMerchantCertificateDtosVal1.setCompanyName("CompanyName322906315");
        _create_dtoBzMerchantCertificateDtosVal1.setCompanyAddress("CompanyAddress-545633598");
        _create_dtoBzMerchantCertificateDtosVal1.setDistServiceType(Long.valueOf(524568635329722080l));
        _create_dtoBzMerchantCertificateDtosVal1.setDistServiceCoverage("DistServiceCoverage2098355587");
        _create_dtoBzMerchantCertificateDtos.add(_create_dtoBzMerchantCertificateDtosVal1);
        _create_dto.getBzMerchantCertificateDtos().addAll(_create_dtoBzMerchantCertificateDtos);
        itaf.WsSellingServiceApplyService.WsPageResult _create__return = port.create(_create_dto);
        System.out.println("create.result=" + _create__return);


        }*/
        {
        System.out.println("Invoking findCertificated...");
        java.lang.Long _findCertificated_userId = Long.valueOf(1l);
        itaf.WsSellingServiceApplyService.WsPageResult _findCertificated__return = port.findCertificated(_findCertificated_userId);
        System.out.println("findCertificated.result=" + _findCertificated__return);


        }
        {
        System.out.println("Invoking findCertificating...");
        java.lang.Long _findCertificating_userId = Long.valueOf(1l);
        itaf.WsSellingServiceApplyService.WsPageResult _findCertificating__return = port.findCertificating(_findCertificating_userId);
        System.out.println("findCertificating.result=" + _findCertificating__return);


        }

        System.exit(0);
    }

}
