
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package itaf.WsSellingServiceApplyService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-29T09:53:30.829+08:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WsSellingServiceApplyService",
                      portName = "WsSellingServiceApplyServiceImplPort",
                      targetNamespace = "http://impl.certificate.server.ws.framework.itaf/",
                      wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsSellingServiceApplyService?wsdl",
                      endpointInterface = "itaf.WsSellingServiceApplyService.WsSellingServiceApplyService")
                      
public class WsSellingServiceApplyServiceImplPortImpl implements WsSellingServiceApplyService {

    private static final Logger LOG = Logger.getLogger(WsSellingServiceApplyServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see itaf.WsSellingServiceApplyService.WsSellingServiceApplyService#create(itaf.WsSellingServiceApplyService.BzSellingServiceApplyDto  dto )*
     */
    public itaf.WsSellingServiceApplyService.WsPageResult create(itaf.WsSellingServiceApplyService.BzSellingServiceApplyDto dto) { 
        LOG.info("Executing operation create");
        System.out.println(dto);
        try {
            itaf.WsSellingServiceApplyService.WsPageResult _return = new itaf.WsSellingServiceApplyService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(-894700425);
            _return.setCurrentPage(1455999004);
            _return.setPageSize(-543361641);
            _return.setStatus("Status1413792513");
            _return.setStatusCode("StatusCode1592331134");
            _return.setTotalCount(1318032497);
            _return.setTotalPage(-666471155);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see itaf.WsSellingServiceApplyService.WsSellingServiceApplyService#findCertificated(java.lang.Long  userId )*
     */
    public itaf.WsSellingServiceApplyService.WsPageResult findCertificated(java.lang.Long userId) { 
        LOG.info("Executing operation findCertificated");
        System.out.println(userId);
        try {
            itaf.WsSellingServiceApplyService.WsPageResult _return = new itaf.WsSellingServiceApplyService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(275144107);
            _return.setCurrentPage(1838691882);
            _return.setPageSize(-1534201480);
            _return.setStatus("Status-200420033");
            _return.setStatusCode("StatusCode-1810774317");
            _return.setTotalCount(-544536982);
            _return.setTotalPage(-2116278800);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see itaf.WsSellingServiceApplyService.WsSellingServiceApplyService#findCertificating(java.lang.Long  userId )*
     */
    public itaf.WsSellingServiceApplyService.WsPageResult findCertificating(java.lang.Long userId) { 
        LOG.info("Executing operation findCertificating");
        System.out.println(userId);
        try {
            itaf.WsSellingServiceApplyService.WsPageResult _return = new itaf.WsSellingServiceApplyService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(-1959215548);
            _return.setCurrentPage(-753997975);
            _return.setPageSize(-1015169941);
            _return.setStatus("Status-370305386");
            _return.setStatusCode("StatusCode-898318794");
            _return.setTotalCount(19465054);
            _return.setTotalPage(1709065274);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
