package itaf.WsSellingServiceApplyService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-29T09:53:30.845+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "itaf.framework.ws.server.certificate", name = "WsSellingServiceApplyService")
@XmlSeeAlso({ObjectFactory.class})
public interface WsSellingServiceApplyService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "itaf.framework.ws.server.certificate", className = "itaf.WsSellingServiceApplyService.Create")
    @WebMethod
    @ResponseWrapper(localName = "createResponse", targetNamespace = "itaf.framework.ws.server.certificate", className = "itaf.WsSellingServiceApplyService.CreateResponse")
    public itaf.WsSellingServiceApplyService.WsPageResult create(
        @WebParam(name = "dto", targetNamespace = "")
        itaf.WsSellingServiceApplyService.BzSellingServiceApplyDto dto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findCertificated", targetNamespace = "itaf.framework.ws.server.certificate", className = "itaf.WsSellingServiceApplyService.FindCertificated")
    @WebMethod
    @ResponseWrapper(localName = "findCertificatedResponse", targetNamespace = "itaf.framework.ws.server.certificate", className = "itaf.WsSellingServiceApplyService.FindCertificatedResponse")
    public itaf.WsSellingServiceApplyService.WsPageResult findCertificated(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findCertificating", targetNamespace = "itaf.framework.ws.server.certificate", className = "itaf.WsSellingServiceApplyService.FindCertificating")
    @WebMethod
    @ResponseWrapper(localName = "findCertificatingResponse", targetNamespace = "itaf.framework.ws.server.certificate", className = "itaf.WsSellingServiceApplyService.FindCertificatingResponse")
    public itaf.WsSellingServiceApplyService.WsPageResult findCertificating(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId
    );
}
