
package itaf.WsOrderService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import itaf.framework.ws.server.order.impl.WsOrderService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-10-10T09:30:22.447+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class WsOrderService_WsOrderServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.order.server.ws.framework.itaf/", "WsOrderService");

    private WsOrderService_WsOrderServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WsOrderService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WsOrderService ss = new WsOrderService(wsdlURL, SERVICE_NAME);
        itaf.WsOrderService.WsOrderService port = ss.getWsOrderServiceImplPort();  
        
        {
        System.out.println("Invoking findPager...");
        java.lang.Long _findPager_userId = Long.valueOf(1l);
        int _findPager_orderStatus = 1;
        int _findPager_currentIndex = 1;
        int _findPager_pageSize = 1;
        itaf.WsOrderService.WsPageResult _findPager__return = port.findPager(_findPager_userId, _findPager_orderStatus, _findPager_currentIndex, _findPager_pageSize);
        System.out.println("findPager.result=" + _findPager__return);


        }
       /* {
        System.out.println("Invoking payment...");
        java.lang.String _payment_cartIds = "_payment_cartIds1759204131";
        itaf.WsOrderService.WsPageResult _payment__return = port.payment(_payment_cartIds);
        System.out.println("payment.result=" + _payment__return);


        }
        {
        System.out.println("Invoking confirmReceived...");
        java.lang.Long _confirmReceived_id = Long.valueOf(4348401020665414061l);
        itaf.WsOrderService.WsPageResult _confirmReceived__return = port.confirmReceived(_confirmReceived_id);
        System.out.println("confirmReceived.result=" + _confirmReceived__return);


        }*/

        System.exit(0);
    }

}
