package itaf.WsOrderService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-10-10T09:30:22.540+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "itaf.framework.ws.server.order", name = "WsOrderService")
@XmlSeeAlso({ObjectFactory.class})
public interface WsOrderService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findPager", targetNamespace = "itaf.framework.ws.server.order", className = "itaf.WsOrderService.FindPager")
    @WebMethod
    @ResponseWrapper(localName = "findPagerResponse", targetNamespace = "itaf.framework.ws.server.order", className = "itaf.WsOrderService.FindPagerResponse")
    public itaf.WsOrderService.WsPageResult findPager(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId,
        @WebParam(name = "orderStatus", targetNamespace = "")
        int orderStatus,
        @WebParam(name = "currentIndex", targetNamespace = "")
        int currentIndex,
        @WebParam(name = "pageSize", targetNamespace = "")
        int pageSize
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "payment", targetNamespace = "itaf.framework.ws.server.order", className = "itaf.WsOrderService.Payment")
    @WebMethod
    @ResponseWrapper(localName = "paymentResponse", targetNamespace = "itaf.framework.ws.server.order", className = "itaf.WsOrderService.PaymentResponse")
    public itaf.WsOrderService.WsPageResult payment(
        @WebParam(name = "cartIds", targetNamespace = "")
        java.lang.String cartIds
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "confirmReceived", targetNamespace = "itaf.framework.ws.server.order", className = "itaf.WsOrderService.ConfirmReceived")
    @WebMethod
    @ResponseWrapper(localName = "confirmReceivedResponse", targetNamespace = "itaf.framework.ws.server.order", className = "itaf.WsOrderService.ConfirmReceivedResponse")
    public itaf.WsOrderService.WsPageResult confirmReceived(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );
}
