
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package itaf.WsSysUserService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-23T17:07:50.678+08:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WsSysUserService",
                      portName = "WsSysUserServiceImplPort",
                      targetNamespace = "http://impl.platform.server.ws.framework.itaf/",
                      wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsSysUserService?wsdl",
                      endpointInterface = "itaf.WsSysUserService.WsSysUserService")
                      
public class WsSysUserServiceImplPortImpl implements WsSysUserService {

    private static final Logger LOG = Logger.getLogger(WsSysUserServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see itaf.WsSysUserService.WsSysUserService#findById(java.lang.Long  userId )*
     */
    public itaf.WsSysUserService.WsPageResult findById(java.lang.Long userId) { 
        LOG.info("Executing operation findById");
        System.out.println(userId);
        try {
            itaf.WsSysUserService.WsPageResult _return = new itaf.WsSysUserService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(-99357805);
            _return.setCurrentPage(-1687448239);
            _return.setPageSize(1679266);
            _return.setStatus("Status-1971898123");
            _return.setStatusCode("StatusCode207353477");
            _return.setTotalCount(502582343);
            _return.setTotalPage(-689900421);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
