package itaf.WsSysUserService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-23T17:07:50.692+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "itaf.framework.ws.server.platform", name = "WsSysUserService")
@XmlSeeAlso({ObjectFactory.class})
public interface WsSysUserService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "itaf.framework.ws.server.platform", className = "itaf.WsSysUserService.FindById")
    @WebMethod
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "itaf.framework.ws.server.platform", className = "itaf.WsSysUserService.FindByIdResponse")
    public itaf.WsSysUserService.WsPageResult findById(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId
    );
}
