package itaf.framework.ws.server.consumer.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-25T10:48:09.959+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "WsUserTakeDeliveryAddressService", 
                  wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsUserTakeDeliveryAddressService?wsdl",
                  targetNamespace = "http://impl.consumer.server.ws.framework.itaf/") 
public class WsUserTakeDeliveryAddressService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://impl.consumer.server.ws.framework.itaf/", "WsUserTakeDeliveryAddressService");
    public static final QName WsUserTakeDeliveryAddressServiceImplPort = new QName("http://impl.consumer.server.ws.framework.itaf/", "WsUserTakeDeliveryAddressServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/itaf-web-side/service/WsUserTakeDeliveryAddressService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsUserTakeDeliveryAddressService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/itaf-web-side/service/WsUserTakeDeliveryAddressService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsUserTakeDeliveryAddressService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsUserTakeDeliveryAddressService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsUserTakeDeliveryAddressService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsUserTakeDeliveryAddressService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsUserTakeDeliveryAddressService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsUserTakeDeliveryAddressService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WsUserTakeDeliveryAddressService
     */
    @WebEndpoint(name = "WsUserTakeDeliveryAddressServiceImplPort")
    public itaf.WsUserTakeDeliveryAddressService.WsUserTakeDeliveryAddressService getWsUserTakeDeliveryAddressServiceImplPort() {
        return super.getPort(WsUserTakeDeliveryAddressServiceImplPort, itaf.WsUserTakeDeliveryAddressService.WsUserTakeDeliveryAddressService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsUserTakeDeliveryAddressService
     */
    @WebEndpoint(name = "WsUserTakeDeliveryAddressServiceImplPort")
    public itaf.WsUserTakeDeliveryAddressService.WsUserTakeDeliveryAddressService getWsUserTakeDeliveryAddressServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WsUserTakeDeliveryAddressServiceImplPort, itaf.WsUserTakeDeliveryAddressService.WsUserTakeDeliveryAddressService.class, features);
    }

}
