
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package itaf.WsProductCategoryService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-18T11:13:10.466+08:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WsProductCategoryService",
                      portName = "WsProductCategoryServiceImplPort",
                      targetNamespace = "http://impl.product.server.ws.framework.itaf/",
                      wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsProductCategoryService?wsdl",
                      endpointInterface = "itaf.WsProductCategoryService.WsProductCategoryService")
                      
public class WsProductCategoryServiceImplPortImpl implements WsProductCategoryService {

    private static final Logger LOG = Logger.getLogger(WsProductCategoryServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see itaf.WsProductCategoryService.WsProductCategoryService#syncToClient(java.lang.String  updateTime )*
     */
    public itaf.WsProductCategoryService.WsPageResult syncToClient(java.lang.String updateTime) { 
        LOG.info("Executing operation syncToClient");
        System.out.println(updateTime);
        try {
            itaf.WsProductCategoryService.WsPageResult _return = new itaf.WsProductCategoryService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(-460035201);
            _return.setCurrentPage(93619004);
            _return.setPageSize(1933385697);
            _return.setStatus("Status1871993350");
            _return.setStatusCode("StatusCode-605740982");
            _return.setTotalCount(1243462075);
            _return.setTotalPage(808589129);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
