package itaf.WsSysRegisterService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-18T10:01:16.807+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "itaf.framework.ws.server.platform", name = "WsSysRegisterService")
@XmlSeeAlso({ObjectFactory.class})
public interface WsSysRegisterService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "itaf.framework.ws.server.platform", className = "itaf.WsSysRegisterService.Register")
    @WebMethod
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "itaf.framework.ws.server.platform", className = "itaf.WsSysRegisterService.RegisterResponse")
    public itaf.WsSysRegisterService.WsPageResult register(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "mobile", targetNamespace = "")
        java.lang.String mobile,
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email,
        @WebParam(name = "nickname", targetNamespace = "")
        java.lang.String nickname
    );
}
