package itaf.WsSysRegisterService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import itaf.framework.ws.server.platform.impl.WsSysRegisterServiceImplService;

/**
 * This class was generated by Apache CXF 3.0.1 2014-09-18T10:01:16.744+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class WsSysRegisterService_WsSysRegisterServiceImplPort_Client {

	private static final QName SERVICE_NAME = new QName(
			"http://impl.platform.server.ws.framework.itaf/",
			"WsSysRegisterServiceImplService");

	private WsSysRegisterService_WsSysRegisterServiceImplPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = WsSysRegisterServiceImplService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		WsSysRegisterServiceImplService ss = new WsSysRegisterServiceImplService(
				wsdlURL, SERVICE_NAME);
		WsSysRegisterService port = ss.getWsSysRegisterServiceImplPort();

		{
			System.out.println("Invoking register...");
			java.lang.String _register_username = "uuuu";
			java.lang.String _register_password = "uuuu";
			java.lang.String _register_mobile = "uuuu";
			java.lang.String _register_email = "uuuu";
			java.lang.String _register_nickname = "uuuu";
			itaf.WsSysRegisterService.WsPageResult _register__return = port
					.register(_register_username, _register_password,
							_register_mobile, _register_email,
							_register_nickname);
			System.out.println("register.result=" + _register__return);

		}

		System.exit(0);
	}

}
