
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package itaf.WsSysRegisterService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-18T10:01:16.791+08:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WsSysRegisterServiceImplService",
                      portName = "WsSysRegisterServiceImplPort",
                      targetNamespace = "http://impl.platform.server.ws.framework.itaf/",
                      wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsSysRegisterService?wsdl",
                      endpointInterface = "itaf.WsSysRegisterService.WsSysRegisterService")
                      
public class WsSysRegisterServiceImplPortImpl implements WsSysRegisterService {

    private static final Logger LOG = Logger.getLogger(WsSysRegisterServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see itaf.WsSysRegisterService.WsSysRegisterService#register(java.lang.String  username ,)java.lang.String  password ,)java.lang.String  mobile ,)java.lang.String  email ,)java.lang.String  nickname )*
     */
    public itaf.WsSysRegisterService.WsPageResult register(java.lang.String username,java.lang.String password,java.lang.String mobile,java.lang.String email,java.lang.String nickname) { 
        LOG.info("Executing operation register");
        System.out.println(username);
        System.out.println(password);
        System.out.println(mobile);
        System.out.println(email);
        System.out.println(nickname);
        try {
            itaf.WsSysRegisterService.WsPageResult _return = new itaf.WsSysRegisterService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(2102715777);
            _return.setCurrentPage(1533836173);
            _return.setPageSize(2045603867);
            _return.setStatus("Status587597465");
            _return.setStatusCode("StatusCode-1986817");
            _return.setTotalCount(1077704748);
            _return.setTotalPage(-2068590213);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
