
package itaf.WsPaymentTypeService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import itaf.framework.ws.server.order.impl.WsPaymentTypeService;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-24T10:33:07.372+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class WsPaymentTypeService_WsPaymentTypeServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.order.server.ws.framework.itaf/", "WsPaymentTypeService");

    private WsPaymentTypeService_WsPaymentTypeServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WsPaymentTypeService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WsPaymentTypeService ss = new WsPaymentTypeService(wsdlURL, SERVICE_NAME);
        itaf.WsPaymentTypeService.WsPaymentTypeService port = ss.getWsPaymentTypeServiceImplPort();  
        
        {
        System.out.println("Invoking findList...");
        itaf.WsPaymentTypeService.WsPageResult _findList__return = port.findList();
        System.out.println("findList.result=" + _findList__return);


        }

        System.exit(0);
    }

}
