
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package itaf.WsPaymentTypeService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-24T10:33:07.419+08:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WsPaymentTypeService",
                      portName = "WsPaymentTypeServiceImplPort",
                      targetNamespace = "http://impl.order.server.ws.framework.itaf/",
                      wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsPaymentTypeService?wsdl",
                      endpointInterface = "itaf.WsPaymentTypeService.WsPaymentTypeService")
                      
public class WsPaymentTypeServiceImplPortImpl implements WsPaymentTypeService {

    private static final Logger LOG = Logger.getLogger(WsPaymentTypeServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see itaf.WsPaymentTypeService.WsPaymentTypeService#findList(*
     */
    public itaf.WsPaymentTypeService.WsPageResult findList() { 
        LOG.info("Executing operation findList");
        try {
            itaf.WsPaymentTypeService.WsPageResult _return = new itaf.WsPaymentTypeService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(1558686287);
            _return.setCurrentPage(-727068766);
            _return.setPageSize(738159862);
            _return.setStatus("Status782731658");
            _return.setStatusCode("StatusCode195975559");
            _return.setTotalCount(-383123329);
            _return.setTotalPage(723649222);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
