package itaf.WsPaymentTypeService;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-24T10:33:07.434+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "itaf.framework.ws.server.order", name = "WsPaymentTypeService")
@XmlSeeAlso({ObjectFactory.class})
public interface WsPaymentTypeService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findList", targetNamespace = "itaf.framework.ws.server.order", className = "itaf.WsPaymentTypeService.FindList")
    @WebMethod
    @ResponseWrapper(localName = "findListResponse", targetNamespace = "itaf.framework.ws.server.order", className = "itaf.WsPaymentTypeService.FindListResponse")
    public itaf.WsPaymentTypeService.WsPageResult findList();
}
