package itaf.framework.ws.server.merchant.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-23T14:10:15.686+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "wsMerchantFavoriteService", 
                  wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsMerchantFavoriteService?wsdl",
                  targetNamespace = "http://impl.merchant.server.ws.framework.itaf/") 
public class WsMerchantFavoriteService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://impl.merchant.server.ws.framework.itaf/", "wsMerchantFavoriteService");
    public static final QName WsMerchantFavoriteServiceImplPort = new QName("http://impl.merchant.server.ws.framework.itaf/", "WsMerchantFavoriteServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/itaf-web-side/service/WsMerchantFavoriteService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsMerchantFavoriteService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/itaf-web-side/service/WsMerchantFavoriteService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsMerchantFavoriteService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsMerchantFavoriteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsMerchantFavoriteService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsMerchantFavoriteService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsMerchantFavoriteService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsMerchantFavoriteService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WsMerchantFavoriteService
     */
    @WebEndpoint(name = "WsMerchantFavoriteServiceImplPort")
    public itaf.WsMerchantFavoriteService.WsMerchantFavoriteService getWsMerchantFavoriteServiceImplPort() {
        return super.getPort(WsMerchantFavoriteServiceImplPort, itaf.WsMerchantFavoriteService.WsMerchantFavoriteService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsMerchantFavoriteService
     */
    @WebEndpoint(name = "WsMerchantFavoriteServiceImplPort")
    public itaf.WsMerchantFavoriteService.WsMerchantFavoriteService getWsMerchantFavoriteServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WsMerchantFavoriteServiceImplPort, itaf.WsMerchantFavoriteService.WsMerchantFavoriteService.class, features);
    }

}
