package itaf.framework.ws.server.merchant.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-18T15:20:07.048+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "WsMerchantService", 
                  wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsMerchantService?wsdl",
                  targetNamespace = "http://impl.merchant.server.ws.framework.itaf/") 
public class WsMerchantService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://impl.merchant.server.ws.framework.itaf/", "WsMerchantService");
    public static final QName WsMerchantServiceImplPort = new QName("http://impl.merchant.server.ws.framework.itaf/", "WsMerchantServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/itaf-web-side/service/WsMerchantService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsMerchantService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/itaf-web-side/service/WsMerchantService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsMerchantService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsMerchantService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsMerchantService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsMerchantService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsMerchantService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsMerchantService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WsMerchantService
     */
    @WebEndpoint(name = "WsMerchantServiceImplPort")
    public itaf.WsMerchantService.WsMerchantService getWsMerchantServiceImplPort() {
        return super.getPort(WsMerchantServiceImplPort, itaf.WsMerchantService.WsMerchantService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsMerchantService
     */
    @WebEndpoint(name = "WsMerchantServiceImplPort")
    public itaf.WsMerchantService.WsMerchantService getWsMerchantServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WsMerchantServiceImplPort, itaf.WsMerchantService.WsMerchantService.class, features);
    }

}
