package itaf.framework.ws.server.product.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-18T11:13:10.497+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "WsProductCategoryService", 
                  wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsProductCategoryService?wsdl",
                  targetNamespace = "http://impl.product.server.ws.framework.itaf/") 
public class WsProductCategoryService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://impl.product.server.ws.framework.itaf/", "WsProductCategoryService");
    public static final QName WsProductCategoryServiceImplPort = new QName("http://impl.product.server.ws.framework.itaf/", "WsProductCategoryServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/itaf-web-side/service/WsProductCategoryService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsProductCategoryService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/itaf-web-side/service/WsProductCategoryService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsProductCategoryService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsProductCategoryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsProductCategoryService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsProductCategoryService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsProductCategoryService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsProductCategoryService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WsProductCategoryService
     */
    @WebEndpoint(name = "WsProductCategoryServiceImplPort")
    public itaf.WsProductCategoryService.WsProductCategoryService getWsProductCategoryServiceImplPort() {
        return super.getPort(WsProductCategoryServiceImplPort, itaf.WsProductCategoryService.WsProductCategoryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsProductCategoryService
     */
    @WebEndpoint(name = "WsProductCategoryServiceImplPort")
    public itaf.WsProductCategoryService.WsProductCategoryService getWsProductCategoryServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WsProductCategoryServiceImplPort, itaf.WsProductCategoryService.WsProductCategoryService.class, features);
    }

}
