
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package itaf.WsLogoutService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-23T11:04:17.647+08:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WsLogoutService",
                      portName = "WsLogoutServiceImplPort",
                      targetNamespace = "http://impl.platform.server.ws.framework.itaf/",
                      wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsLogoutService?wsdl",
                      endpointInterface = "itaf.WsLogoutService.WsLogoutService")
                      
public class WsLogoutServiceImplPortImpl implements WsLogoutService {

    private static final Logger LOG = Logger.getLogger(WsLogoutServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see itaf.WsLogoutService.WsLogoutService#logout(java.lang.Long  userId )*
     */
    public itaf.WsLogoutService.WsPageResult logout(java.lang.Long userId) { 
        LOG.info("Executing operation logout");
        System.out.println(userId);
        try {
            itaf.WsLogoutService.WsPageResult _return = new itaf.WsLogoutService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(1625474886);
            _return.setCurrentPage(1173219155);
            _return.setPageSize(1107636307);
            _return.setStatus("Status758010931");
            _return.setStatusCode("StatusCode-1073296985");
            _return.setTotalCount(509044931);
            _return.setTotalPage(1000513055);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
