package itaf.WsStockOrderService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import itaf.framework.ws.server.merchant.impl.WsStockOrderService;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.1 2014-09-24T18:01:30.939+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class WsStockOrderService_WsStockOrderServiceImplPort_Client {

	private static final QName SERVICE_NAME = new QName(
			"http://impl.merchant.server.ws.framework.itaf/",
			"WsStockOrderService");

	private WsStockOrderService_WsStockOrderServiceImplPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = WsStockOrderService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		WsStockOrderService ss = new WsStockOrderService(wsdlURL, SERVICE_NAME);
		itaf.WsStockOrderService.WsStockOrderService port = ss
				.getWsStockOrderServiceImplPort();

		{
			System.out.println("Invoking create...");
			java.lang.String _create_orderIds = "_create_orderIds-525450757";
			java.lang.Long _create_merchantId = Long
					.valueOf(-4695151481402074068l);
			itaf.WsStockOrderService.WsPageResult _create__return = port
					.create(_create_orderIds, _create_merchantId);
			System.out.println("create.result=" + _create__return);

		}

		System.exit(0);
	}

}
