package itaf.framework.ws.server.search.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-25T11:50:12.853+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "WsSearchService", 
                  wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsSearchService?wsdl",
                  targetNamespace = "http://impl.search.server.ws.framework.itaf/") 
public class WsSearchService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://impl.search.server.ws.framework.itaf/", "WsSearchService");
    public static final QName WsSearchServiceImplPort = new QName("http://impl.search.server.ws.framework.itaf/", "WsSearchServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/itaf-web-side/service/WsSearchService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsSearchService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/itaf-web-side/service/WsSearchService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsSearchService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsSearchService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsSearchService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsSearchService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsSearchService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsSearchService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WsSearchService
     */
    @WebEndpoint(name = "WsSearchServiceImplPort")
    public itaf.WsSearchService.WsSearchService getWsSearchServiceImplPort() {
        return super.getPort(WsSearchServiceImplPort, itaf.WsSearchService.WsSearchService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsSearchService
     */
    @WebEndpoint(name = "WsSearchServiceImplPort")
    public itaf.WsSearchService.WsSearchService getWsSearchServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WsSearchServiceImplPort, itaf.WsSearchService.WsSearchService.class, features);
    }

}
