package itaf.WsDistributionServiceApplyService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-10-09T09:54:21.735+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "itaf.framework.ws.server.certificate", name = "WsDistributionServiceApplyService")
@XmlSeeAlso({ObjectFactory.class})
public interface WsDistributionServiceApplyService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "itaf.framework.ws.server.certificate", className = "itaf.WsDistributionServiceApplyService.Create")
    @WebMethod
    @ResponseWrapper(localName = "createResponse", targetNamespace = "itaf.framework.ws.server.certificate", className = "itaf.WsDistributionServiceApplyService.CreateResponse")
    public itaf.WsDistributionServiceApplyService.WsPageResult create(
        @WebParam(name = "dto", targetNamespace = "")
        itaf.WsDistributionServiceApplyService.BzDistServiceApplyDto dto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findCertificated", targetNamespace = "itaf.framework.ws.server.certificate", className = "itaf.WsDistributionServiceApplyService.FindCertificated")
    @WebMethod
    @ResponseWrapper(localName = "findCertificatedResponse", targetNamespace = "itaf.framework.ws.server.certificate", className = "itaf.WsDistributionServiceApplyService.FindCertificatedResponse")
    public itaf.WsDistributionServiceApplyService.WsPageResult findCertificated(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findCertificating", targetNamespace = "itaf.framework.ws.server.certificate", className = "itaf.WsDistributionServiceApplyService.FindCertificating")
    @WebMethod
    @ResponseWrapper(localName = "findCertificatingResponse", targetNamespace = "itaf.framework.ws.server.certificate", className = "itaf.WsDistributionServiceApplyService.FindCertificatingResponse")
    public itaf.WsDistributionServiceApplyService.WsPageResult findCertificating(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId
    );
}
