package itaf.WsDistributionServiceApplyService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import itaf.framework.ws.server.certificate.impl.WsDistributionServiceApplyService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1 2014-10-09T09:54:21.610+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class WsDistributionServiceApplyService_WsDistributionServiceApplyServiceImplPort_Client {

	private static final QName SERVICE_NAME = new QName(
			"http://impl.certificate.server.ws.framework.itaf/",
			"WsDistributionServiceApplyService");

	private WsDistributionServiceApplyService_WsDistributionServiceApplyServiceImplPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = WsDistributionServiceApplyService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		WsDistributionServiceApplyService ss = new WsDistributionServiceApplyService(
				wsdlURL, SERVICE_NAME);
		itaf.WsDistributionServiceApplyService.WsDistributionServiceApplyService port = ss
				.getWsDistributionServiceApplyServiceImplPort();

		/*{
			System.out.println("Invoking create...");
			itaf.WsDistributionServiceApplyService.BzDistServiceApplyDto _create_dto = new itaf.WsDistributionServiceApplyService.BzDistServiceApplyDto();
			_create_dto.setId(Long.valueOf(8739115549610164188l));
			_create_dto.setObjId(Long.valueOf(6835886941047711997l));
			_create_dto.setCreatedBy(Long.valueOf(-8298385631941698489l));
			_create_dto.setCreatedDate(javax.xml.datatype.DatatypeFactory
					.newInstance().newXMLGregorianCalendar(
							"2014-10-09T09:54:21.657+08:00"));
			_create_dto.setUpdatedBy(Long.valueOf(2841030657896921891l));
			_create_dto.setUpdatedDate(javax.xml.datatype.DatatypeFactory
					.newInstance().newXMLGregorianCalendar(
							"2014-10-09T09:54:21.657+08:00"));
			_create_dto.setMarkForDelete(Boolean.valueOf(false));
			itaf.WsDistributionServiceApplyService.SysUserDto _create_dtoSysUserDto = new itaf.WsDistributionServiceApplyService.SysUserDto();
			_create_dtoSysUserDto.setId(Long.valueOf(386336827721698355l));
			_create_dtoSysUserDto.setObjId(Long.valueOf(-8498389546096845026l));
			_create_dtoSysUserDto.setCreatedBy(Long
					.valueOf(-908659764782822941l));
			_create_dtoSysUserDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-10-09T09:54:21.657+08:00"));
			_create_dtoSysUserDto.setUpdatedBy(Long
					.valueOf(7969310386334883257l));
			_create_dtoSysUserDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-10-09T09:54:21.657+08:00"));
			_create_dtoSysUserDto.setMarkForDelete(Boolean.valueOf(true));
			_create_dtoSysUserDto.setUsername("Username1083373190");
			_create_dtoSysUserDto.setPassword("Password1797153001");
			_create_dtoSysUserDto.setMobile("Mobile1575974848");
			_create_dtoSysUserDto.setType(Long.valueOf(-6245892254313190513l));
			_create_dtoSysUserDto.setEmail("Email1663239085");
			_create_dtoSysUserDto.setNickname("Nickname1145932777");
			java.util.List<itaf.WsDistributionServiceApplyService.SysRoleDto> _create_dtoSysUserDtoSysRoles = new java.util.ArrayList<itaf.WsDistributionServiceApplyService.SysRoleDto>();
			itaf.WsDistributionServiceApplyService.SysRoleDto _create_dtoSysUserDtoSysRolesVal1 = new itaf.WsDistributionServiceApplyService.SysRoleDto();
			_create_dtoSysUserDtoSysRolesVal1.setId(Long
					.valueOf(6120931604385016194l));
			_create_dtoSysUserDtoSysRolesVal1.setObjId(Long
					.valueOf(2068538618431916730l));
			_create_dtoSysUserDtoSysRolesVal1.setCreatedBy(Long
					.valueOf(6919518910284123389l));
			_create_dtoSysUserDtoSysRolesVal1
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-10-09T09:54:21.657+08:00"));
			_create_dtoSysUserDtoSysRolesVal1.setUpdatedBy(Long
					.valueOf(5558976309934628138l));
			_create_dtoSysUserDtoSysRolesVal1
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-10-09T09:54:21.657+08:00"));
			_create_dtoSysUserDtoSysRolesVal1.setMarkForDelete(Boolean
					.valueOf(true));
			_create_dtoSysUserDtoSysRolesVal1.setNameZh("NameZh2025132027");
			_create_dtoSysUserDtoSysRolesVal1.setNameEn("NameEn1429688342");
			_create_dtoSysUserDtoSysRolesVal1
					.setDescription("Description949162376");
			java.util.List<itaf.WsDistributionServiceApplyService.SysResourceDto> _create_dtoSysUserDtoSysRolesVal1SysResourceDtos = new java.util.ArrayList<itaf.WsDistributionServiceApplyService.SysResourceDto>();
			_create_dtoSysUserDtoSysRolesVal1.getSysResourceDtos().addAll(
					_create_dtoSysUserDtoSysRolesVal1SysResourceDtos);
			java.util.List<itaf.WsDistributionServiceApplyService.SysUserDto> _create_dtoSysUserDtoSysRolesVal1SysUserDtos = new java.util.ArrayList<itaf.WsDistributionServiceApplyService.SysUserDto>();
			_create_dtoSysUserDtoSysRolesVal1.getSysUserDtos().addAll(
					_create_dtoSysUserDtoSysRolesVal1SysUserDtos);
			_create_dtoSysUserDtoSysRoles
					.add(_create_dtoSysUserDtoSysRolesVal1);
			_create_dtoSysUserDto.getSysRoles().addAll(
					_create_dtoSysUserDtoSysRoles);
			_create_dto.setSysUserDto(_create_dtoSysUserDto);
			_create_dto.setBzAttachmentId(Long.valueOf(-4580204288262153385l));
			_create_dto.setCompanyName("CompanyName947694158");
			_create_dto.setDistServiceType(Long.valueOf(-4352110443886194232l));
			_create_dto.setDistServiceCoverage(Long
					.valueOf(6168784215189767483l));
			_create_dto.setApprovalStatus(Long.valueOf(-7129711633175735733l));
			_create_dto.setBzWorkflowId(Long.valueOf(4967210677287026447l));
			java.util.List<itaf.WsDistributionServiceApplyService.BzMerchantCertificateDto> _create_dtoBzMerchantCertificateDtos = new java.util.ArrayList<itaf.WsDistributionServiceApplyService.BzMerchantCertificateDto>();
			itaf.WsDistributionServiceApplyService.BzMerchantCertificateDto _create_dtoBzMerchantCertificateDtosVal1 = new itaf.WsDistributionServiceApplyService.BzMerchantCertificateDto();
			_create_dtoBzMerchantCertificateDtosVal1.setId(Long
					.valueOf(6679514444460936358l));
			_create_dtoBzMerchantCertificateDtosVal1.setObjId(Long
					.valueOf(-7992959027998222312l));
			_create_dtoBzMerchantCertificateDtosVal1.setCreatedBy(Long
					.valueOf(-7448410593858201721l));
			_create_dtoBzMerchantCertificateDtosVal1
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-10-09T09:54:21.657+08:00"));
			_create_dtoBzMerchantCertificateDtosVal1.setUpdatedBy(Long
					.valueOf(-1761400002914290451l));
			_create_dtoBzMerchantCertificateDtosVal1
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-10-09T09:54:21.657+08:00"));
			_create_dtoBzMerchantCertificateDtosVal1.setMarkForDelete(Boolean
					.valueOf(false));
			itaf.WsDistributionServiceApplyService.BzDistServiceApplyDto _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto = new itaf.WsDistributionServiceApplyService.BzDistServiceApplyDto();
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto
					.setId(Long.valueOf(-3923658938024504250l));
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto
					.setObjId(Long.valueOf(-8407006765120770653l));
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto
					.setCreatedBy(Long.valueOf(-2397275094396665147l));
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-10-09T09:54:21.657+08:00"));
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto
					.setUpdatedBy(Long.valueOf(-8139396755872224552l));
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-10-09T09:54:21.657+08:00"));
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto
					.setMarkForDelete(Boolean.valueOf(false));
			itaf.WsDistributionServiceApplyService.SysUserDto _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto = new itaf.WsDistributionServiceApplyService.SysUserDto();
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto
					.setId(Long.valueOf(4067317755709499845l));
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto
					.setObjId(Long.valueOf(5710693983428556963l));
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto
					.setCreatedBy(Long.valueOf(6854324954654076078l));
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-10-09T09:54:21.657+08:00"));
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto
					.setUpdatedBy(Long.valueOf(-4403618257903173979l));
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-10-09T09:54:21.657+08:00"));
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto
					.setMarkForDelete(Boolean.valueOf(false));
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto
					.setUsername("Username276161370");
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto
					.setPassword("Password-973817263");
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto
					.setMobile("Mobile-2074876950");
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto
					.setType(Long.valueOf(3969024384280348778l));
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto
					.setEmail("Email-1829862761");
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto
					.setNickname("Nickname1005872787");
			java.util.List<itaf.WsDistributionServiceApplyService.SysRoleDto> _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDtoSysRoles = new java.util.ArrayList<itaf.WsDistributionServiceApplyService.SysRoleDto>();
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto
					.getSysRoles()
					.addAll(_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDtoSysRoles);
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto
					.setSysUserDto(_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoSysUserDto);
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto
					.setBzAttachmentId(Long.valueOf(6297255789280417074l));
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto
					.setCompanyName("CompanyName-1884119000");
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto
					.setDistServiceType(Long.valueOf(3645424649938086599l));
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto
					.setDistServiceCoverage(Long.valueOf(5909336191473485696l));
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto
					.setApprovalStatus(Long.valueOf(3086388720692681360l));
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto
					.setBzWorkflowId(Long.valueOf(-3764906676967123160l));
			java.util.List<itaf.WsDistributionServiceApplyService.BzMerchantCertificateDto> _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoBzMerchantCertificateDtos = new java.util.ArrayList<itaf.WsDistributionServiceApplyService.BzMerchantCertificateDto>();
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto
					.getBzMerchantCertificateDtos()
					.addAll(_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoBzMerchantCertificateDtos);
			java.util.List<itaf.WsDistributionServiceApplyService.BzApprovalInfoDto> _create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoBzApprovalInfoList = new java.util.ArrayList<itaf.WsDistributionServiceApplyService.BzApprovalInfoDto>();
			_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto
					.getBzApprovalInfoList()
					.addAll(_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDtoBzApprovalInfoList);
			_create_dtoBzMerchantCertificateDtosVal1
					.setBzDistServiceApplyDto(_create_dtoBzMerchantCertificateDtosVal1BzDistServiceApplyDto);
			itaf.WsDistributionServiceApplyService.BzSellingServiceApplyDto _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto = new itaf.WsDistributionServiceApplyService.BzSellingServiceApplyDto();
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto
					.setId(Long.valueOf(8581536806887083109l));
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto
					.setObjId(Long.valueOf(4291106900911407708l));
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto
					.setCreatedBy(Long.valueOf(-2036528238944462814l));
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-10-09T09:54:21.657+08:00"));
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto
					.setUpdatedBy(Long.valueOf(-8681926657539571219l));
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-10-09T09:54:21.657+08:00"));
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto
					.setMarkForDelete(Boolean.valueOf(true));
			itaf.WsDistributionServiceApplyService.SysUserDto _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto = new itaf.WsDistributionServiceApplyService.SysUserDto();
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto
					.setId(Long.valueOf(-2358339437437568919l));
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto
					.setObjId(Long.valueOf(8314048885568739401l));
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto
					.setCreatedBy(Long.valueOf(5006441712256152258l));
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-10-09T09:54:21.657+08:00"));
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto
					.setUpdatedBy(Long.valueOf(-9077939118888713082l));
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-10-09T09:54:21.657+08:00"));
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto
					.setMarkForDelete(Boolean.valueOf(true));
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto
					.setUsername("Username162553034");
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto
					.setPassword("Password765495432");
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto
					.setMobile("Mobile1307279362");
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto
					.setType(Long.valueOf(-4030719688171686433l));
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto
					.setEmail("Email233037484");
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto
					.setNickname("Nickname-1542190945");
			java.util.List<itaf.WsDistributionServiceApplyService.SysRoleDto> _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDtoSysRoles = new java.util.ArrayList<itaf.WsDistributionServiceApplyService.SysRoleDto>();
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto
					.getSysRoles()
					.addAll(_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDtoSysRoles);
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto
					.setSysUserDto(_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoSysUserDto);
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto
					.setBzAttachmentId(Long.valueOf(181133078528311021l));
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto
					.setCompanyName("CompanyName-567487039");
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto
					.setCompanyAddress("CompanyAddress-1178128673");
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto
					.setApprovalStatus(Long.valueOf(-6677069508523065378l));
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto
					.setBzWorkflowId(Long.valueOf(3253886818610944627l));
			java.util.List<itaf.WsDistributionServiceApplyService.BzMerchantCertificateDto> _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoBzMerchantCertificateDtos = new java.util.ArrayList<itaf.WsDistributionServiceApplyService.BzMerchantCertificateDto>();
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto
					.getBzMerchantCertificateDtos()
					.addAll(_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoBzMerchantCertificateDtos);
			java.util.List<itaf.WsDistributionServiceApplyService.BzApprovalInfoDto> _create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoBzApprovalInfoList = new java.util.ArrayList<itaf.WsDistributionServiceApplyService.BzApprovalInfoDto>();
			_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto
					.getBzApprovalInfoList()
					.addAll(_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDtoBzApprovalInfoList);
			_create_dtoBzMerchantCertificateDtosVal1
					.setBzSellingServiceApplyDto(_create_dtoBzMerchantCertificateDtosVal1BzSellingServiceApplyDto);
			_create_dtoBzMerchantCertificateDtosVal1.setSysUserId(Long
					.valueOf(-7714188275552260015l));
			_create_dtoBzMerchantCertificateDtosVal1.setCertificateType(Long
					.valueOf(7507515685981307922l));
			_create_dtoBzMerchantCertificateDtosVal1
					.setCompanyName("CompanyName-1026041391");
			_create_dtoBzMerchantCertificateDtosVal1
					.setCompanyAddress("CompanyAddress-1946929271");
			_create_dtoBzMerchantCertificateDtosVal1.setDistServiceType(Long
					.valueOf(5367507996267378828l));
			_create_dtoBzMerchantCertificateDtosVal1
					.setDistServiceCoverage("DistServiceCoverage18470084");
			_create_dtoBzMerchantCertificateDtos
					.add(_create_dtoBzMerchantCertificateDtosVal1);
			_create_dto.getBzMerchantCertificateDtos().addAll(
					_create_dtoBzMerchantCertificateDtos);
			java.util.List<itaf.WsDistributionServiceApplyService.BzApprovalInfoDto> _create_dtoBzApprovalInfoList = new java.util.ArrayList<itaf.WsDistributionServiceApplyService.BzApprovalInfoDto>();
			itaf.WsDistributionServiceApplyService.BzApprovalInfoDto _create_dtoBzApprovalInfoListVal1 = new itaf.WsDistributionServiceApplyService.BzApprovalInfoDto();
			_create_dtoBzApprovalInfoListVal1.setId(Long
					.valueOf(-192960274662881718l));
			_create_dtoBzApprovalInfoListVal1.setObjId(Long
					.valueOf(-2516393859686304751l));
			_create_dtoBzApprovalInfoListVal1.setCreatedBy(Long
					.valueOf(7697593062997906695l));
			_create_dtoBzApprovalInfoListVal1
					.setCreatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-10-09T09:54:21.657+08:00"));
			_create_dtoBzApprovalInfoListVal1.setUpdatedBy(Long
					.valueOf(-2009224429948209580l));
			_create_dtoBzApprovalInfoListVal1
					.setUpdatedDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-10-09T09:54:21.673+08:00"));
			_create_dtoBzApprovalInfoListVal1.setMarkForDelete(Boolean
					.valueOf(false));
			_create_dtoBzApprovalInfoListVal1
					.setProcessInstanceId("ProcessInstanceId-1634274085");
			_create_dtoBzApprovalInfoListVal1.setTaskId("TaskId-607217573");
			_create_dtoBzApprovalInfoListVal1
					.setBussinessKey("BussinessKey-996181897");
			_create_dtoBzApprovalInfoListVal1
					.setActivityName("ActivityName-222377017");
			_create_dtoBzApprovalInfoListVal1
					.setApprovalName("ApprovalName1263722011");
			_create_dtoBzApprovalInfoListVal1
					.setApprovalState("ApprovalState256609302");
			_create_dtoBzApprovalInfoListVal1
					.setApprovalInfo("ApprovalInfo-2129189324");
			_create_dtoBzApprovalInfoListVal1
					.setApprovalTime(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-10-09T09:54:21.673+08:00"));
			_create_dtoBzApprovalInfoList
					.add(_create_dtoBzApprovalInfoListVal1);
			_create_dto.getBzApprovalInfoList().addAll(
					_create_dtoBzApprovalInfoList);
			itaf.WsDistributionServiceApplyService.WsPageResult _create__return = port
					.create(_create_dto);
			System.out.println("create.result=" + _create__return);

		}*/
		{
			System.out.println("Invoking findCertificated...");
			java.lang.Long _findCertificated_userId = Long
					.valueOf(1l);
			itaf.WsDistributionServiceApplyService.WsPageResult _findCertificated__return = port
					.findCertificated(_findCertificated_userId);
			System.out.println("findCertificated.result="
					+ _findCertificated__return);

		}
		{
			System.out.println("Invoking findCertificating...");
			java.lang.Long _findCertificating_userId = Long
					.valueOf(1l);
			itaf.WsDistributionServiceApplyService.WsPageResult _findCertificating__return = port
					.findCertificating(_findCertificating_userId);
			System.out.println("findCertificating.result="
					+ _findCertificating__return);

		}

		System.exit(0);
	}

}
