
package itaf.WsProductService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import itaf.framework.ws.server.product.impl.WsProductService;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-18T14:17:59.225+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class WsProductService_WsProductServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.product.server.ws.framework.itaf/", "WsProductService");

    private WsProductService_WsProductServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WsProductService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WsProductService ss = new WsProductService(wsdlURL, SERVICE_NAME);
        itaf.WsProductService.WsProductService port = ss.getWsProductServiceImplPort();  
        
      /* {
        System.out.println("Invoking deleteByIds...");
        java.lang.String _deleteByIds_ids = "2";
        itaf.WsProductService.WsPageResult _deleteByIds__return = port.deleteByIds(_deleteByIds_ids);
        System.out.println("deleteByIds.result=" + _deleteByIds__return);


        }*/
        {
        System.out.println("Invoking removeProductsFromShelf...");
        java.lang.String _removeProductsFromShelf_ids = "2";
        itaf.WsProductService.WsPageResult _removeProductsFromShelf__return = port.removeProductsFromShelf(_removeProductsFromShelf_ids);
        System.out.println("removeProductsFromShelf.result=" + _removeProductsFromShelf__return);


        }
        /*{
        System.out.println("Invoking getById...");
        java.lang.Long _getById_id = Long.valueOf(2l);
        itaf.WsProductService.WsPageResult _getById__return = port.getById(_getById_id);
        System.out.println("getById.result=" + _getById__return);


        }*/
        /*{
         System.out.println("Invoking createOrUpdate...");
        java.lang.Long _createOrUpdate_userId = Long.valueOf(3856322188111085244l);
        itaf.WsProductService.BzProductDto _createOrUpdate_dto = new itaf.WsProductService.BzProductDto();
        _createOrUpdate_dto.setMarkForDelete(false);
        _createOrUpdate_dto.setCreatedBy(Long.valueOf(-5357997101353430135l));
        _createOrUpdate_dto.setCreatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-18T14:17:59.303+08:00"));
        _createOrUpdate_dto.setUpdatedBy("UpdatedBy-1532916580");
        _createOrUpdate_dto.setUpdatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-18T14:17:59.350+08:00"));
        
        java.util.List<javax.xml.bind.JAXBElement<? extends java.lang.Object>> _createOrUpdate_dtoRest = new java.util.ArrayList<javax.xml.bind.JAXBElement<? extends java.lang.Object>>();
        javax.xml.bind.JAXBElement<? extends java.lang.Object> _createOrUpdate_dtoRestVal1 = null;
        _createOrUpdate_dtoRest.add(_createOrUpdate_dtoRestVal1);
        _createOrUpdate_dto.getRest().addAll(_createOrUpdate_dtoRest);
        itaf.WsProductService.WsPageResult _createOrUpdate__return = port.createOrUpdate(_createOrUpdate_userId, _createOrUpdate_dto);
        System.out.println("createOrUpdate.result=" + _createOrUpdate__return);


        }*/
        /*{
        System.out.println("Invoking putProductsOnShelf...");
        java.lang.String _putProductsOnShelf_ids = "2";
        itaf.WsProductService.WsPageResult _putProductsOnShelf__return = port.putProductsOnShelf(_putProductsOnShelf_ids);
        System.out.println("putProductsOnShelf.result=" + _putProductsOnShelf__return);


        }*/

        System.exit(0);
    }

}
