package itaf.WsDistributionOrderService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-23T10:34:45.590+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "itaf.framework.ws.server.merchant", name = "WsDistributionOrderService")
@XmlSeeAlso({ObjectFactory.class})
public interface WsDistributionOrderService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "itaf.framework.ws.server.merchant", className = "itaf.WsDistributionOrderService.Create")
    @WebMethod
    @ResponseWrapper(localName = "createResponse", targetNamespace = "itaf.framework.ws.server.merchant", className = "itaf.WsDistributionOrderService.CreateResponse")
    public itaf.WsDistributionOrderService.WsPageResult create(
        @WebParam(name = "orderCodes", targetNamespace = "")
        java.lang.String orderCodes
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getById", targetNamespace = "itaf.framework.ws.server.merchant", className = "itaf.WsDistributionOrderService.GetById")
    @WebMethod
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "itaf.framework.ws.server.merchant", className = "itaf.WsDistributionOrderService.GetByIdResponse")
    public itaf.WsDistributionOrderService.WsPageResult getById(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findPager", targetNamespace = "itaf.framework.ws.server.merchant", className = "itaf.WsDistributionOrderService.FindPager")
    @WebMethod
    @ResponseWrapper(localName = "findPagerResponse", targetNamespace = "itaf.framework.ws.server.merchant", className = "itaf.WsDistributionOrderService.FindPagerResponse")
    public itaf.WsDistributionOrderService.WsPageResult findPager(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId,
        @WebParam(name = "orderType", targetNamespace = "")
        int orderType,
        @WebParam(name = "currentIndex", targetNamespace = "")
        int currentIndex,
        @WebParam(name = "pageSize", targetNamespace = "")
        int pageSize
    );
}
