package itaf.WsDistributionOrderService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import itaf.framework.ws.server.merchant.impl.WsDistributionOrderService;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.1 2014-09-23T10:34:45.512+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class WsDistributionOrderService_WsDistributionOrderServiceImplPort_Client {

	private static final QName SERVICE_NAME = new QName(
			"http://impl.merchant.server.ws.framework.itaf/",
			"WsDistributionOrderService");

	private WsDistributionOrderService_WsDistributionOrderServiceImplPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = WsDistributionOrderService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		WsDistributionOrderService ss = new WsDistributionOrderService(wsdlURL,
				SERVICE_NAME);
		itaf.WsDistributionOrderService.WsDistributionOrderService port = ss
				.getWsDistributionOrderServiceImplPort();

		{
			System.out.println("Invoking create...");
			java.lang.String _create_orderCodes = "1";
			itaf.WsDistributionOrderService.WsPageResult _create__return = port
					.create(_create_orderCodes);
			System.out.println("create.result=" + _create__return);

		}
		/*{
			System.out.println("Invoking getById...");
			java.lang.Long _getById_id = Long.valueOf(1l);
			itaf.WsDistributionOrderService.WsPageResult _getById__return = port
					.getById(_getById_id);
			System.out.println("getById.result=" + _getById__return);

		}
		{
			System.out.println("Invoking findPager...");
			java.lang.Long _findPager_userId = Long
					.valueOf(1l);
			int _findPager_orderType = 2;
			int _findPager_currentIndex = 0;
			int _findPager_pageSize = 1;
			itaf.WsDistributionOrderService.WsPageResult _findPager__return = port
					.findPager(_findPager_userId, _findPager_orderType,
							_findPager_currentIndex, _findPager_pageSize);
			System.out.println("findPager.result=" + _findPager__return);

		}*/

		System.exit(0);
	}

}
