
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package itaf.WsDistributionOrderService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-23T10:34:45.558+08:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WsDistributionOrderService",
                      portName = "WsDistributionOrderServiceImplPort",
                      targetNamespace = "http://impl.merchant.server.ws.framework.itaf/",
                      wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsDistributionOrderService?wsdl",
                      endpointInterface = "itaf.WsDistributionOrderService.WsDistributionOrderService")
                      
public class WsDistributionOrderServiceImplPortImpl implements WsDistributionOrderService {

    private static final Logger LOG = Logger.getLogger(WsDistributionOrderServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see itaf.WsDistributionOrderService.WsDistributionOrderService#create(java.lang.String  orderCodes )*
     */
    public itaf.WsDistributionOrderService.WsPageResult create(java.lang.String orderCodes) { 
        LOG.info("Executing operation create");
        System.out.println(orderCodes);
        try {
            itaf.WsDistributionOrderService.WsPageResult _return = new itaf.WsDistributionOrderService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(-68583627);
            _return.setCurrentPage(190931596);
            _return.setPageSize(-364839263);
            _return.setStatus("Status146063325");
            _return.setStatusCode("StatusCode1450612154");
            _return.setTotalCount(462894019);
            _return.setTotalPage(616239633);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see itaf.WsDistributionOrderService.WsDistributionOrderService#getById(java.lang.Long  id )*
     */
    public itaf.WsDistributionOrderService.WsPageResult getById(java.lang.Long id) { 
        LOG.info("Executing operation getById");
        System.out.println(id);
        try {
            itaf.WsDistributionOrderService.WsPageResult _return = new itaf.WsDistributionOrderService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(-232967886);
            _return.setCurrentPage(156224803);
            _return.setPageSize(1015546848);
            _return.setStatus("Status13393800");
            _return.setStatusCode("StatusCode102570071");
            _return.setTotalCount(493925080);
            _return.setTotalPage(424608300);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see itaf.WsDistributionOrderService.WsDistributionOrderService#findPager(java.lang.Long  userId ,)int  orderType ,)int  currentIndex ,)int  pageSize )*
     */
    public itaf.WsDistributionOrderService.WsPageResult findPager(java.lang.Long userId,int orderType,int currentIndex,int pageSize) { 
        LOG.info("Executing operation findPager");
        System.out.println(userId);
        System.out.println(orderType);
        System.out.println(currentIndex);
        System.out.println(pageSize);
        try {
            itaf.WsDistributionOrderService.WsPageResult _return = new itaf.WsDistributionOrderService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(-291669313);
            _return.setCurrentPage(784024747);
            _return.setPageSize(628398051);
            _return.setStatus("Status-857444473");
            _return.setStatusCode("StatusCode-2141549700");
            _return.setTotalCount(1666355269);
            _return.setTotalPage(-321978154);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
