package itaf.WsSearchService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-25T11:50:12.853+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "itaf.framework.ws.server.search", name = "WsSearchService")
@XmlSeeAlso({ObjectFactory.class})
public interface WsSearchService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBzMerchantDtoObject", targetNamespace = "itaf.framework.ws.server.search", className = "itaf.WsSearchService.GetBzMerchantDtoObject")
    @WebMethod
    @ResponseWrapper(localName = "getBzMerchantDtoObjectResponse", targetNamespace = "itaf.framework.ws.server.search", className = "itaf.WsSearchService.GetBzMerchantDtoObjectResponse")
    public itaf.WsSearchService.BzMerchantDto getBzMerchantDtoObject();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "searchProducts", targetNamespace = "itaf.framework.ws.server.search", className = "itaf.WsSearchService.SearchProducts")
    @WebMethod
    @ResponseWrapper(localName = "searchProductsResponse", targetNamespace = "itaf.framework.ws.server.search", className = "itaf.WsSearchService.SearchProductsResponse")
    public itaf.WsSearchService.WsPageResult searchProducts(
        @WebParam(name = "queryMap", targetNamespace = "")
        itaf.WsSearchService.SearchProducts.QueryMap queryMap,
        @WebParam(name = "currentIndex", targetNamespace = "")
        int currentIndex,
        @WebParam(name = "pageSize", targetNamespace = "")
        int pageSize
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBzDistributionCompanyDtoObject", targetNamespace = "itaf.framework.ws.server.search", className = "itaf.WsSearchService.GetBzDistributionCompanyDtoObject")
    @WebMethod
    @ResponseWrapper(localName = "getBzDistributionCompanyDtoObjectResponse", targetNamespace = "itaf.framework.ws.server.search", className = "itaf.WsSearchService.GetBzDistributionCompanyDtoObjectResponse")
    public itaf.WsSearchService.BzDistributionCompanyDto getBzDistributionCompanyDtoObject();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBzProductDtoObject", targetNamespace = "itaf.framework.ws.server.search", className = "itaf.WsSearchService.GetBzProductDtoObject")
    @WebMethod
    @ResponseWrapper(localName = "getBzProductDtoObjectResponse", targetNamespace = "itaf.framework.ws.server.search", className = "itaf.WsSearchService.GetBzProductDtoObjectResponse")
    public itaf.WsSearchService.BzProductDto getBzProductDtoObject();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "searchMerchants", targetNamespace = "itaf.framework.ws.server.search", className = "itaf.WsSearchService.SearchMerchants")
    @WebMethod
    @ResponseWrapper(localName = "searchMerchantsResponse", targetNamespace = "itaf.framework.ws.server.search", className = "itaf.WsSearchService.SearchMerchantsResponse")
    public itaf.WsSearchService.WsPageResult searchMerchants(
        @WebParam(name = "queryMap", targetNamespace = "")
        itaf.WsSearchService.SearchMerchants.QueryMap queryMap,
        @WebParam(name = "currentIndex", targetNamespace = "")
        int currentIndex,
        @WebParam(name = "pageSize", targetNamespace = "")
        int pageSize
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "searchDistributionCompanys", targetNamespace = "itaf.framework.ws.server.search", className = "itaf.WsSearchService.SearchDistributionCompanys")
    @WebMethod
    @ResponseWrapper(localName = "searchDistributionCompanysResponse", targetNamespace = "itaf.framework.ws.server.search", className = "itaf.WsSearchService.SearchDistributionCompanysResponse")
    public itaf.WsSearchService.WsPageResult searchDistributionCompanys(
        @WebParam(name = "queryMap", targetNamespace = "")
        itaf.WsSearchService.SearchDistributionCompanys.QueryMap queryMap,
        @WebParam(name = "currentIndex", targetNamespace = "")
        int currentIndex,
        @WebParam(name = "pageSize", targetNamespace = "")
        int pageSize
    );
}
