
package itaf.WsCollectionOrderService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import itaf.framework.ws.server.merchant.impl.WsCollectionOrderService;

import java.io.File;
import java.math.BigDecimal;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-19T15:15:43.605+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class WsCollectionOrderService_WsCollectionOrderServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.merchant.server.ws.framework.itaf/", "WsCollectionOrderService");

    private WsCollectionOrderService_WsCollectionOrderServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WsCollectionOrderService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WsCollectionOrderService ss = new WsCollectionOrderService(wsdlURL, SERVICE_NAME);
        itaf.WsCollectionOrderService.WsCollectionOrderService port = ss.getWsCollectionOrderServiceImplPort();  
        
        {
        System.out.println("Invoking confirmCollection...");
        itaf.WsCollectionOrderService.BzCollectionOrderDto _confirmCollection_bzCollectionOrderDto = new itaf.WsCollectionOrderService.BzCollectionOrderDto();

        _confirmCollection_bzCollectionOrderDto.setId(1l);
        _confirmCollection_bzCollectionOrderDto.setActualAmount(new BigDecimal(200));
        itaf.WsCollectionOrderService.WsPageResult _confirmCollection__return = port.confirmCollection(_confirmCollection_bzCollectionOrderDto);
        System.out.println("confirmCollection.result=" + _confirmCollection__return);


        }

        System.exit(0);
    }

}
