
package itaf.WsRealnameCertificateService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import itaf.framework.ws.server.certificate.impl.WsRealnameCertificateService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-10-09T09:43:16.457+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class WsRealnameCertificateService_WsRealnameCertificateServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.certificate.server.ws.framework.itaf/", "WsRealnameCertificateService");

    private WsRealnameCertificateService_WsRealnameCertificateServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WsRealnameCertificateService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WsRealnameCertificateService ss = new WsRealnameCertificateService(wsdlURL, SERVICE_NAME);
        itaf.WsRealnameCertificateService.WsRealnameCertificateService port = ss.getWsRealnameCertificateServiceImplPort();  
        
        {
        System.out.println("Invoking findCertificated...");
        java.lang.Long _findCertificated_userId = Long.valueOf(-1919984683254040653l);
        itaf.WsRealnameCertificateService.WsPageResult _findCertificated__return = port.findCertificated(1l);
        System.out.println("findCertificated.result=" + _findCertificated__return);


        }
       /* {
        System.out.println("Invoking findCertificating...");
        java.lang.Long _findCertificating_userId = Long.valueOf(-6837914010495013835l);
        itaf.WsRealnameCertificateService.WsPageResult _findCertificating__return = port.findCertificating(_findCertificating_userId);
        System.out.println("findCertificating.result=" + _findCertificating__return);


        }*/

        System.exit(0);
    }

}
