package itaf.WsRealnameCertificateService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-10-09T09:43:16.520+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "itaf.framework.ws.server.certificate", name = "WsRealnameCertificateService")
@XmlSeeAlso({ObjectFactory.class})
public interface WsRealnameCertificateService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findCertificated", targetNamespace = "itaf.framework.ws.server.certificate", className = "itaf.WsRealnameCertificateService.FindCertificated")
    @WebMethod
    @ResponseWrapper(localName = "findCertificatedResponse", targetNamespace = "itaf.framework.ws.server.certificate", className = "itaf.WsRealnameCertificateService.FindCertificatedResponse")
    public itaf.WsRealnameCertificateService.WsPageResult findCertificated(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findCertificating", targetNamespace = "itaf.framework.ws.server.certificate", className = "itaf.WsRealnameCertificateService.FindCertificating")
    @WebMethod
    @ResponseWrapper(localName = "findCertificatingResponse", targetNamespace = "itaf.framework.ws.server.certificate", className = "itaf.WsRealnameCertificateService.FindCertificatingResponse")
    public itaf.WsRealnameCertificateService.WsPageResult findCertificating(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId
    );
}
