
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package itaf.WsRealnameCertificateService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-10-09T09:43:16.504+08:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WsRealnameCertificateService",
                      portName = "WsRealnameCertificateServiceImplPort",
                      targetNamespace = "http://impl.certificate.server.ws.framework.itaf/",
                      wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsRealnameCertificateService?wsdl",
                      endpointInterface = "itaf.WsRealnameCertificateService.WsRealnameCertificateService")
                      
public class WsRealnameCertificateServiceImplPortImpl implements WsRealnameCertificateService {

    private static final Logger LOG = Logger.getLogger(WsRealnameCertificateServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see itaf.WsRealnameCertificateService.WsRealnameCertificateService#findCertificated(java.lang.Long  userId )*
     */
    public itaf.WsRealnameCertificateService.WsPageResult findCertificated(java.lang.Long userId) { 
        LOG.info("Executing operation findCertificated");
        System.out.println(userId);
        try {
            itaf.WsRealnameCertificateService.WsPageResult _return = new itaf.WsRealnameCertificateService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(623646460);
            _return.setCurrentPage(-1594337434);
            _return.setPageSize(-742607798);
            _return.setStatus("Status-622610140");
            _return.setStatusCode("StatusCode-1197838358");
            _return.setTotalCount(765221056);
            _return.setTotalPage(-234409050);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see itaf.WsRealnameCertificateService.WsRealnameCertificateService#findCertificating(java.lang.Long  userId )*
     */
    public itaf.WsRealnameCertificateService.WsPageResult findCertificating(java.lang.Long userId) { 
        LOG.info("Executing operation findCertificating");
        System.out.println(userId);
        try {
            itaf.WsRealnameCertificateService.WsPageResult _return = new itaf.WsRealnameCertificateService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(802612868);
            _return.setCurrentPage(-237600356);
            _return.setPageSize(-1484425914);
            _return.setStatus("Status-2081547781");
            _return.setStatusCode("StatusCode1890750532");
            _return.setTotalCount(-326152597);
            _return.setTotalPage(-229396056);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
