package itaf.WsMerchantFavoriteService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-23T14:10:15.686+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "itaf.framework.ws.server.merchant", name = "WsMerchantFavoriteService")
@XmlSeeAlso({ObjectFactory.class})
public interface WsMerchantFavoriteService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findPagerByUserId", targetNamespace = "itaf.framework.ws.server.merchant", className = "itaf.WsMerchantFavoriteService.FindPagerByUserId")
    @WebMethod
    @ResponseWrapper(localName = "findPagerByUserIdResponse", targetNamespace = "itaf.framework.ws.server.merchant", className = "itaf.WsMerchantFavoriteService.FindPagerByUserIdResponse")
    public itaf.WsMerchantFavoriteService.WsPageResult findPagerByUserId(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId,
        @WebParam(name = "currentIndex", targetNamespace = "")
        int currentIndex,
        @WebParam(name = "pageSize", targetNamespace = "")
        int pageSize
    );
}
