
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package itaf.WsMerchantService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-18T15:20:07.017+08:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WsMerchantService",
                      portName = "WsMerchantServiceImplPort",
                      targetNamespace = "http://impl.merchant.server.ws.framework.itaf/",
                      wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsMerchantService?wsdl",
                      endpointInterface = "itaf.WsMerchantService.WsMerchantService")
                      
public class WsMerchantServiceImplPortImpl implements WsMerchantService {

    private static final Logger LOG = Logger.getLogger(WsMerchantServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see itaf.WsMerchantService.WsMerchantService#getById(java.lang.Long  id )*
     */
    public itaf.WsMerchantService.WsPageResult getById(java.lang.Long id) { 
        LOG.info("Executing operation getById");
        System.out.println(id);
        try {
            itaf.WsMerchantService.WsPageResult _return = new itaf.WsMerchantService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(-1577293490);
            _return.setCurrentPage(-1375298742);
            _return.setPageSize(-1076286093);
            _return.setStatus("Status-34469385");
            _return.setStatusCode("StatusCode-1232453693");
            _return.setTotalCount(-2001801682);
            _return.setTotalPage(1225911196);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
