package itaf.WsMerchantService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-18T15:20:07.048+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "itaf.framework.ws.server.merchant", name = "WsMerchantService")
@XmlSeeAlso({ObjectFactory.class})
public interface WsMerchantService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getById", targetNamespace = "itaf.framework.ws.server.merchant", className = "itaf.WsMerchantService.GetById")
    @WebMethod
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "itaf.framework.ws.server.merchant", className = "itaf.WsMerchantService.GetByIdResponse")
    public itaf.WsMerchantService.WsPageResult getById(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );
}
