
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package itaf.WsCartItemService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-19T10:49:22.755+08:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WsCartItemService",
                      portName = "WsCartItemServiceImplPort",
                      targetNamespace = "http://impl.cart.server.ws.framework.itaf/",
                      wsdlLocation = "http://localhost:8080/itaf-web-side/service/WsCartItemService?wsdl",
                      endpointInterface = "itaf.WsCartItemService.WsCartItemService")
                      
public class WsCartItemServiceImplPortImpl implements WsCartItemService {

    private static final Logger LOG = Logger.getLogger(WsCartItemServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see itaf.WsCartItemService.WsCartItemService#putProductInCartItem(itaf.WsCartItemService.BzCartItemDto  dto )*
     */
    public itaf.WsCartItemService.WsPageResult putProductInCartItem(itaf.WsCartItemService.BzCartItemDto dto) { 
        LOG.info("Executing operation putProductInCartItem");
        System.out.println(dto);
        try {
            itaf.WsCartItemService.WsPageResult _return = new itaf.WsCartItemService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(-1419217838);
            _return.setCurrentPage(569395955);
            _return.setPageSize(-1623570500);
            _return.setStatus("Status1616350059");
            _return.setStatusCode("StatusCode-871947883");
            _return.setTotalCount(-938583809);
            _return.setTotalPage(1444846176);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see itaf.WsCartItemService.WsCartItemService#deleteByIds(java.lang.String  ids )*
     */
    public itaf.WsCartItemService.WsPageResult deleteByIds(java.lang.String ids) { 
        LOG.info("Executing operation deleteByIds");
        System.out.println(ids);
        try {
            itaf.WsCartItemService.WsPageResult _return = new itaf.WsCartItemService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(-475764155);
            _return.setCurrentPage(-727221507);
            _return.setPageSize(1912463541);
            _return.setStatus("Status63089408");
            _return.setStatusCode("StatusCode1306076152");
            _return.setTotalCount(-1692787914);
            _return.setTotalPage(1388494274);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see itaf.WsCartItemService.WsCartItemService#findListByUserId(java.lang.Long  userId )*
     */
    public itaf.WsCartItemService.WsPageResult findListByUserId(java.lang.Long userId) { 
        LOG.info("Executing operation findListByUserId");
        System.out.println(userId);
        try {
            itaf.WsCartItemService.WsPageResult _return = new itaf.WsCartItemService.WsPageResult();
            java.util.List<java.lang.Object> _returnContent = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnContentVal1 = null;
            _returnContent.add(_returnContentVal1);
            _return.getContent().addAll(_returnContent);
            _return.setCurrentIndex(611595237);
            _return.setCurrentPage(-1433593051);
            _return.setPageSize(1277603223);
            _return.setStatus("Status1094198921");
            _return.setStatusCode("StatusCode1580551277");
            _return.setTotalCount(-879819349);
            _return.setTotalPage(-441841330);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
