package itaf.WsCartItemService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-19T10:49:22.771+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "itaf.framework.ws.server.cart", name = "WsCartItemService")
@XmlSeeAlso({ObjectFactory.class})
public interface WsCartItemService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "putProductInCartItem", targetNamespace = "itaf.framework.ws.server.cart", className = "itaf.WsCartItemService.PutProductInCartItem")
    @WebMethod
    @ResponseWrapper(localName = "putProductInCartItemResponse", targetNamespace = "itaf.framework.ws.server.cart", className = "itaf.WsCartItemService.PutProductInCartItemResponse")
    public itaf.WsCartItemService.WsPageResult putProductInCartItem(
        @WebParam(name = "dto", targetNamespace = "")
        itaf.WsCartItemService.BzCartItemDto dto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteByIds", targetNamespace = "itaf.framework.ws.server.cart", className = "itaf.WsCartItemService.DeleteByIds")
    @WebMethod
    @ResponseWrapper(localName = "deleteByIdsResponse", targetNamespace = "itaf.framework.ws.server.cart", className = "itaf.WsCartItemService.DeleteByIdsResponse")
    public itaf.WsCartItemService.WsPageResult deleteByIds(
        @WebParam(name = "ids", targetNamespace = "")
        java.lang.String ids
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findListByUserId", targetNamespace = "itaf.framework.ws.server.cart", className = "itaf.WsCartItemService.FindListByUserId")
    @WebMethod
    @ResponseWrapper(localName = "findListByUserIdResponse", targetNamespace = "itaf.framework.ws.server.cart", className = "itaf.WsCartItemService.FindListByUserIdResponse")
    public itaf.WsCartItemService.WsPageResult findListByUserId(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId
    );
}
